extends RefCounted

# ===== IMPROVEMENTS #1101-1200: Combat, UI, Quality of Life & Polish =====
# These improvements cover combat depth, UI polish, quality of life features,
# visual effects, audio cues, progression systems, and overall game polish.

static func get_improvements() -> Array[Dictionary]:
	return [
		# --- Combat Depth (#1101-1120) ---
		{"id": 1101, "name": "Combo Counter UI", "category": "combat", "desc": "HUD displays current combo count with escalating colors and size."},
		{"id": 1102, "name": "Combo Damage Multiplier", "category": "combat", "desc": "Higher combos increase damage by 2% per hit up to 50% bonus."},
		{"id": 1103, "name": "Combo Timer Bar", "category": "combat", "desc": "Visual timer bar shows remaining time before combo resets."},
		{"id": 1104, "name": "Critical Hit Flash", "category": "combat", "desc": "Screen briefly flashes white on critical hits for impact."},
		{"id": 1105, "name": "Backstab Bonus", "category": "combat", "desc": "Attacking enemies from behind deals 50% extra damage."},
		{"id": 1106, "name": "Dodge Counter Window", "category": "combat", "desc": "Perfect dodge timing opens a brief counter-attack window for 2x damage."},
		{"id": 1107, "name": "Weapon Trails", "category": "combat", "desc": "Melee attacks leave colored trails matching weapon rarity."},
		{"id": 1108, "name": "Projectile Homing", "category": "combat", "desc": "Rare+ ranged weapons have slight projectile homing toward enemies."},
		{"id": 1109, "name": "Shield Bash", "category": "combat", "desc": "Blocking while moving forward performs a shield bash stun."},
		{"id": 1110, "name": "Elemental Damage Types", "category": "combat", "desc": "Weapons can deal fire, ice, lightning, or poison elemental damage."},
		{"id": 1111, "name": "Fire DoT Effect", "category": "combat", "desc": "Fire damage applies burning for 3 seconds dealing 10% weapon damage/sec."},
		{"id": 1112, "name": "Ice Slow Effect", "category": "combat", "desc": "Ice damage slows enemies by 30% for 2 seconds."},
		{"id": 1113, "name": "Lightning Chain", "category": "combat", "desc": "Lightning damage chains to one nearby enemy for 50% damage."},
		{"id": 1114, "name": "Poison Stack", "category": "combat", "desc": "Poison damage stacks up to 5 times, each stack deals 3% max HP/sec."},
		{"id": 1115, "name": "Knockback Force Scaling", "category": "combat", "desc": "Heavier weapons knock enemies back further based on damage dealt."},
		{"id": 1116, "name": "Parry System", "category": "combat", "desc": "Blocking at the exact moment of enemy attack reflects 50% damage."},
		{"id": 1117, "name": "Finisher Moves", "category": "combat", "desc": "Low HP enemies can be executed with E key for bonus XP and gold."},
		{"id": 1118, "name": "Area of Effect Attacks", "category": "combat", "desc": "Charged heavy attacks deal damage in a wider arc to multiple enemies."},
		{"id": 1119, "name": "Lifesteal on Kill", "category": "combat", "desc": "Killing an enemy restores 5% of max HP as lifesteal."},
		{"id": 1120, "name": "Rage Mode", "category": "combat", "desc": "At 100 rage, activate rage mode for 30% damage boost and speed for 10s."},

		# --- UI Polish (#1121-1140) ---
		{"id": 1121, "name": "Minimap Room Icons", "category": "ui", "desc": "Minimap shows room type icons for explored rooms."},
		{"id": 1122, "name": "Minimap Player Arrow", "category": "ui", "desc": "Player shown as a directional arrow on the minimap."},
		{"id": 1123, "name": "Minimap Enemy Dots", "category": "ui", "desc": "Nearby enemies shown as red dots on the minimap."},
		{"id": 1124, "name": "Minimap Item Markers", "category": "ui", "desc": "Uncollected items shown as yellow dots on the minimap."},
		{"id": 1125, "name": "Boss Health Bar", "category": "ui", "desc": "Large health bar appears at top of screen for boss enemies."},
		{"id": 1126, "name": "Damage Numbers Variety", "category": "ui", "desc": "Different damage types show different colored numbers (fire=orange, ice=blue)."},
		{"id": 1127, "name": "XP Progress Bar", "category": "ui", "desc": "Smooth animated XP bar with level-up flash effect."},
		{"id": 1128, "name": "Kill Feed", "category": "ui", "desc": "Small scrolling feed showing recent kills with enemy name and XP gained."},
		{"id": 1129, "name": "Status Effect Icons", "category": "ui", "desc": "Active buffs and debuffs shown as icons below health bar."},
		{"id": 1130, "name": "Crosshair Feedback", "category": "ui", "desc": "Crosshair changes color and expands when hovering over enemies."},
		{"id": 1131, "name": "Low Health Warning", "category": "ui", "desc": "Screen edges pulse red when player HP is below 25%."},
		{"id": 1132, "name": "Room Clear Indicator", "category": "ui", "desc": "Green checkmark appears when all enemies in current room are defeated."},
		{"id": 1133, "name": "Auto-Map Reveal", "category": "ui", "desc": "Minimap auto-reveals rooms as the player explores."},
		{"id": 1134, "name": "Loot Rarity Beam", "category": "ui", "desc": "Rare+ items emit a vertical light beam visible from distance."},
		{"id": 1135, "name": "Notification Queue", "category": "ui", "desc": "Multiple notifications stack and display sequentially instead of overlapping."},
		{"id": 1136, "name": "Quick-Use Consumable Slot", "category": "ui", "desc": "Number key 4 uses the first consumable in inventory without opening menu."},
		{"id": 1137, "name": "Gold Pickup Animation", "category": "ui", "desc": "Gold coins fly toward the HUD gold counter when collected."},
		{"id": 1138, "name": "Mission Timer Display", "category": "ui", "desc": "Mission timer displayed in top-right corner of HUD."},
		{"id": 1139, "name": "DPS Meter", "category": "ui", "desc": "Optional DPS meter tracks damage per second over rolling 10-second window."},
		{"id": 1140, "name": "Death Screen Stats", "category": "ui", "desc": "Death screen shows full mission stats: kills, time, damage, items found."},

		# --- Quality of Life (#1141-1160) ---
		{"id": 1141, "name": "Auto-Equip Best Gear", "category": "qol", "desc": "Option to auto-equip better items when picked up."},
		{"id": 1142, "name": "Item Comparison Tooltip", "category": "qol", "desc": "Hovering items shows stat difference from currently equipped piece."},
		{"id": 1143, "name": "Junk Auto-Sell", "category": "qol", "desc": "Common items auto-sold for gold when inventory is full."},
		{"id": 1144, "name": "Quick Loot All", "category": "qol", "desc": "Hold E near items to quickly pick up all nearby items."},
		{"id": 1145, "name": "Map Ping System", "category": "qol", "desc": "Click minimap to place a waypoint marker visible in the game world."},
		{"id": 1146, "name": "Quick Restart Hotkey", "category": "qol", "desc": "Press R on death screen to quickly restart the mission."},
		{"id": 1147, "name": "Skip Tutorial Option", "category": "qol", "desc": "Settings toggle to disable tutorial popups for experienced players."},
		{"id": 1148, "name": "Control Remapping", "category": "qol", "desc": "Settings screen allows rebinding all key controls."},
		{"id": 1149, "name": "Colorblind Mode", "category": "qol", "desc": "Alternative color schemes for rarity and damage types for accessibility."},
		{"id": 1150, "name": "Font Size Scaling", "category": "qol", "desc": "UI font size slider for better readability on different screens."},
		{"id": 1151, "name": "Auto-Save on Room Clear", "category": "qol", "desc": "Game auto-saves progress when a room is fully cleared of enemies."},
		{"id": 1152, "name": "Loot Filter", "category": "qol", "desc": "Filter auto-pickup by rarity threshold (e.g., only pick up Rare+ items)."},
		{"id": 1153, "name": "Inventory Search", "category": "qol", "desc": "Search bar in inventory to find items by name."},
		{"id": 1154, "name": "Item Lock", "category": "qol", "desc": "Lock items to prevent accidental selling or discarding."},
		{"id": 1155, "name": "Stat Comparison Panel", "category": "qol", "desc": "Side-by-side comparison when hovering equipment vs what's equipped."},
		{"id": 1156, "name": "Bulk Sell Interface", "category": "qol", "desc": "Select multiple items at once to sell in bulk."},
		{"id": 1157, "name": "Pickup Magnet", "category": "qol", "desc": "Items within 100px are pulled toward the player automatically."},
		{"id": 1158, "name": "Sprint Auto-Toggle", "category": "qol", "desc": "Option to toggle sprint on/off instead of holding the key."},
		{"id": 1159, "name": "Camera Zoom Scroll Wheel", "category": "qol", "desc": "Mouse scroll wheel adjusts camera zoom in real-time."},
		{"id": 1160, "name": "Pause on Focus Loss", "category": "qol", "desc": "Game automatically pauses when the window loses focus."},

		# --- Visual Effects (#1161-1180) ---
		{"id": 1161, "name": "Footstep Dust", "category": "vfx", "desc": "Small dust particles appear at player's feet when running."},
		{"id": 1162, "name": "Blood Splatter Decals", "category": "vfx", "desc": "Permanent blood splatter decals left on floor from combat."},
		{"id": 1163, "name": "Torch Flicker Animation", "category": "vfx", "desc": "Torch lights flicker with randomized intensity for atmosphere."},
		{"id": 1164, "name": "Death Dissolve Effect", "category": "vfx", "desc": "Enemies dissolve into particles on death instead of just disappearing."},
		{"id": 1165, "name": "Level Up Fanfare", "category": "vfx", "desc": "Radial burst of golden particles and light on level up."},
		{"id": 1166, "name": "Rarity Glow Aura", "category": "vfx", "desc": "Equipment emits a subtle colored aura matching its rarity."},
		{"id": 1167, "name": "Healing Green Particles", "category": "vfx", "desc": "Green crosses float upward when healing effects trigger."},
		{"id": 1168, "name": "Poison Bubble Particles", "category": "vfx", "desc": "Green bubbles float off poisoned entities."},
		{"id": 1169, "name": "Frozen Ice Crystal", "category": "vfx", "desc": "Frozen enemies get ice crystal overlay effect."},
		{"id": 1170, "name": "Burning Flame Particles", "category": "vfx", "desc": "Burning enemies have flame particles rising from them."},
		{"id": 1171, "name": "Dodge Afterimage", "category": "vfx", "desc": "Transparent afterimage left behind during dodge roll."},
		{"id": 1172, "name": "Impact Ripple", "category": "vfx", "desc": "Circular ripple effect emanates from heavy melee impacts."},
		{"id": 1173, "name": "Sprint Speed Lines", "category": "vfx", "desc": "Subtle speed lines at screen edges while sprinting."},
		{"id": 1174, "name": "Chest Open Animation", "category": "vfx", "desc": "Treasure chests play an opening animation with sparkle particles."},
		{"id": 1175, "name": "Portal Swirl Effect", "category": "vfx", "desc": "Safe spaces have a swirling portal visual effect."},
		{"id": 1176, "name": "Fog of War", "category": "vfx", "desc": "Unexplored areas covered in dark fog that recedes as player explores."},
		{"id": 1177, "name": "Environmental Particles", "category": "vfx", "desc": "Room-type specific ambient particles (embers in lava rooms, snowflakes in ice)."},
		{"id": 1178, "name": "Weapon Glow on Equip", "category": "vfx", "desc": "Weapon emoji pulses with rarity color briefly when equipped."},
		{"id": 1179, "name": "Shield Block Sparks", "category": "vfx", "desc": "Spark particles fly when successfully blocking an attack."},
		{"id": 1180, "name": "Boss Death Explosion", "category": "vfx", "desc": "Large explosion effect with screen flash when a boss enemy dies."},

		# --- Progression & Meta (#1181-1200) ---
		{"id": 1181, "name": "Achievement System", "category": "progression", "desc": "Track achievements for kills, collection, exploration milestones."},
		{"id": 1182, "name": "Achievement Popup", "category": "progression", "desc": "Toast notification slides in when an achievement is unlocked."},
		{"id": 1183, "name": "Persistent Upgrades", "category": "progression", "desc": "Spend gold between runs to permanently upgrade base stats."},
		{"id": 1184, "name": "Unlock New Races", "category": "progression", "desc": "Complete challenges to unlock new playable races."},
		{"id": 1185, "name": "Unlock New Classes", "category": "progression", "desc": "Complete challenges to unlock new class specializations."},
		{"id": 1186, "name": "Bestiary", "category": "progression", "desc": "Catalog of all encountered enemy types with stats and lore."},
		{"id": 1187, "name": "Item Codex", "category": "progression", "desc": "Collection log of all item types ever found."},
		{"id": 1188, "name": "Run History", "category": "progression", "desc": "Log of previous runs with stats, rating, and items found."},
		{"id": 1189, "name": "Daily Challenge", "category": "progression", "desc": "Daily seeded dungeon with leaderboard for competitive play."},
		{"id": 1190, "name": "Difficulty Tiers", "category": "progression", "desc": "Unlock harder difficulty tiers with better loot by completing previous tier."},
		{"id": 1191, "name": "Mastery Levels", "category": "progression", "desc": "Each weapon type gains mastery XP for improved handling."},
		{"id": 1192, "name": "Skill Tree", "category": "progression", "desc": "Branching skill tree for each class with active and passive abilities."},
		{"id": 1193, "name": "Enchantment System", "category": "progression", "desc": "Add enchantments to equipment using materials found in dungeons."},
		{"id": 1194, "name": "Crafting Recipes", "category": "progression", "desc": "Combine materials to craft specific items and consumables."},
		{"id": 1195, "name": "Pet Companions", "category": "progression", "desc": "Unlock pet companions that follow the player and provide passive bonuses."},
		{"id": 1196, "name": "Starship Upgrades", "category": "progression", "desc": "Upgrade starship rooms for better pre-mission bonuses."},
		{"id": 1197, "name": "NPC Reputation", "category": "progression", "desc": "Build reputation with NPCs for better shop prices and unique quests."},
		{"id": 1198, "name": "Prestige System", "category": "progression", "desc": "Reset progress for permanent multipliers and cosmetic rewards."},
		{"id": 1199, "name": "Leaderboard Integration", "category": "progression", "desc": "Global leaderboards for speedruns, highest level, and most kills."},
		{"id": 1200, "name": "Seasonal Events", "category": "progression", "desc": "Rotating seasonal events with unique enemies, items, and challenges."},
	]
