extends RefCounted

# ===== IMPROVEMENTS #1001-1100: Starship, Inventory, Pause Menu & Integration =====
# These improvements cover the new starship hub, inventory system, pause menu,
# NPC interactions, deployment flow, and further game polish.

static func get_improvements() -> Array[Dictionary]:
	return [
		# --- Starship Hub (#1001-1020) ---
		{"id": 1001, "name": "Starship Starting Hub", "category": "starship", "desc": "Player begins each run on an orbiting starship before deploying to the surface."},
		{"id": 1002, "name": "Bridge Command Center", "category": "starship", "desc": "The bridge features navigation consoles and viewscreens showing the graveworld."},
		{"id": 1003, "name": "Armory Room", "category": "starship", "desc": "Weapon racks and armor lockers let players equip before deploying."},
		{"id": 1004, "name": "Medbay Healing Station", "category": "starship", "desc": "Fully heal at the medbay before each mission."},
		{"id": 1005, "name": "Cargo Bay Storage", "category": "starship", "desc": "Supply crates in the cargo bay contain random loot."},
		{"id": 1006, "name": "Engine Room", "category": "starship", "desc": "FTL drive and power core area with radiation hazard warnings."},
		{"id": 1007, "name": "Crew Quarters Save Point", "category": "starship", "desc": "Rest at the bunk to save your game progress."},
		{"id": 1008, "name": "Hangar Bay Deployment", "category": "starship", "desc": "Board the drop pod in the hangar to deploy to the dungeon surface."},
		{"id": 1009, "name": "Mess Hall Food", "category": "starship", "desc": "Eat at the mess hall food dispenser to restore health."},
		{"id": 1010, "name": "Research Lab", "category": "starship", "desc": "Analyze artifacts and research upgrades at the science terminal."},
		{"id": 1011, "name": "Airlock Emergency Exit", "category": "starship", "desc": "Emergency airlock room - purely decorative danger zone."},
		{"id": 1012, "name": "Storage Compartment", "category": "starship", "desc": "Extra storage room for overflow inventory and supplies."},
		{"id": 1013, "name": "Starship Sci-Fi Lighting", "category": "starship", "desc": "Cool blue-white lighting throughout the starship interior."},
		{"id": 1014, "name": "Starship Tile Rendering", "category": "starship", "desc": "Sci-fi checkerboard floor pattern with grid lines and detail accents."},
		{"id": 1015, "name": "Starship Wall Panels", "category": "starship", "desc": "Wall tiles with panel details and blinking status lights."},
		{"id": 1016, "name": "Room Color Coding", "category": "starship", "desc": "Each starship room has a unique color tint for easy identification."},
		{"id": 1017, "name": "Room Labels", "category": "starship", "desc": "Decorative room name labels with emoji icons above each room."},
		{"id": 1018, "name": "Starship Wall Collisions", "category": "starship", "desc": "Full wall collision and light occluder system for starship interior."},
		{"id": 1019, "name": "Starship View Culling", "category": "starship", "desc": "Camera-based culling for efficient starship map rendering."},
		{"id": 1020, "name": "Symmetrical Ship Layout", "category": "starship", "desc": "Ship rooms are laid out in a logical symmetrical design."},

		# --- NPC System (#1021-1035) ---
		{"id": 1021, "name": "Captain Voss NPC", "category": "npc", "desc": "Captain on the bridge gives mission briefing and lore context."},
		{"id": 1022, "name": "Dr. Chen Medic NPC", "category": "npc", "desc": "Medic in medbay offers healing services and health tips."},
		{"id": 1023, "name": "Sgt. Drake Quartermaster", "category": "npc", "desc": "Quartermaster in armory lets you pick your loadout."},
		{"id": 1024, "name": "Chief Torres Engineer", "category": "npc", "desc": "Engineer in the engine room provides ship status updates."},
		{"id": 1025, "name": "Prof. Nakamura Scientist", "category": "npc", "desc": "Scientist in lab requests artifacts and provides research upgrades."},
		{"id": 1026, "name": "NPC Emoji Portraits", "category": "npc", "desc": "Each NPC displays a unique emoji portrait above their position."},
		{"id": 1027, "name": "NPC Name Tags", "category": "npc", "desc": "NPCs show their name below their emoji in a distinct color."},
		{"id": 1028, "name": "NPC Proximity Detection", "category": "npc", "desc": "NPCs detect when the player is nearby and show interaction prompts."},
		{"id": 1029, "name": "NPC Dialogue System", "category": "npc", "desc": "Full dialogue UI with emoji portrait, name, text, and navigation."},
		{"id": 1030, "name": "Multi-Line Dialogue", "category": "npc", "desc": "NPCs support multiple dialogue lines with Space/E to advance."},
		{"id": 1031, "name": "NPC Bob Animation", "category": "npc", "desc": "NPC emojis gently bob up and down for a living feel."},
		{"id": 1032, "name": "Dialogue Pause", "category": "npc", "desc": "Game pauses while reading NPC dialogue for uninterrupted conversations."},
		{"id": 1033, "name": "NPC Interaction Signal", "category": "npc", "desc": "NPCs emit a signal when interacted with for extensible behavior."},
		{"id": 1034, "name": "Dialogue Close on Escape", "category": "npc", "desc": "Press Escape to close NPC dialogue at any time."},
		{"id": 1035, "name": "NPC Prompt Pulse", "category": "npc", "desc": "The [E] interaction prompt pulses with a subtle alpha animation."},

		# --- Inventory System (#1036-1060) ---
		{"id": 1036, "name": "Inventory Manager", "category": "inventory", "desc": "Full inventory management system with add, remove, stack, and search."},
		{"id": 1037, "name": "Equipment Slots", "category": "inventory", "desc": "9 equipment slots: weapon, offhand, helmet, chest, boots, ring1, ring2, amulet, trinket."},
		{"id": 1038, "name": "Item Stacking", "category": "inventory", "desc": "Stackable items (consumables, materials) stack up to 99."},
		{"id": 1039, "name": "40-Slot Inventory", "category": "inventory", "desc": "Player inventory holds up to 40 unique item stacks."},
		{"id": 1040, "name": "Item Rarity Tiers", "category": "inventory", "desc": "6 rarity tiers: common, uncommon, rare, epic, legendary, mythic."},
		{"id": 1041, "name": "Item Categories", "category": "inventory", "desc": "Items categorized as weapon, armor, consumable, material, quest, or misc."},
		{"id": 1042, "name": "Equip/Unequip Items", "category": "inventory", "desc": "Click equipment to equip; click equipped slot to unequip back to inventory."},
		{"id": 1043, "name": "Use Consumables", "category": "inventory", "desc": "Click consumables in inventory to use them immediately."},
		{"id": 1044, "name": "Sort by Rarity", "category": "inventory", "desc": "Sort inventory by rarity with highest rarity items first."},
		{"id": 1045, "name": "Sort by Name", "category": "inventory", "desc": "Sort inventory alphabetically by item name."},
		{"id": 1046, "name": "Sort by Category", "category": "inventory", "desc": "Sort inventory by item category (weapons, armor, consumables, etc.)."},
		{"id": 1047, "name": "Item Tooltips", "category": "inventory", "desc": "Hover over items to see detailed tooltips with stats and description."},
		{"id": 1048, "name": "Rarity-Colored Borders", "category": "inventory", "desc": "Item slots have colored borders matching their rarity tier."},
		{"id": 1049, "name": "Equipment Stat Bonuses", "category": "inventory", "desc": "Equipped items provide cumulative stat bonuses displayed in the UI."},
		{"id": 1050, "name": "Random Item Generation", "category": "inventory", "desc": "Procedural item generation with random stats, names, and rarity."},
		{"id": 1051, "name": "Weapon Generation", "category": "inventory", "desc": "Random weapons: swords, axes, hammers, bows, staves, daggers."},
		{"id": 1052, "name": "Armor Generation", "category": "inventory", "desc": "Random armor pieces for helmet, chest, and boots slots."},
		{"id": 1053, "name": "Accessory Generation", "category": "inventory", "desc": "Random rings, amulets, and charms with 1-3 random stat bonuses."},
		{"id": 1054, "name": "Consumable Generation", "category": "inventory", "desc": "Random consumables: health/mana/stamina potions, antidotes, tonics."},
		{"id": 1055, "name": "Rarity-Scaled Stats", "category": "inventory", "desc": "Higher rarity items have proportionally better stats."},
		{"id": 1056, "name": "Level-Scaled Items", "category": "inventory", "desc": "Generated items scale with player level for appropriate power."},
		{"id": 1057, "name": "Rarity Prefixes", "category": "inventory", "desc": "Items get thematic name prefixes based on rarity (Worn, Enchanted, Godforged, etc.)."},
		{"id": 1058, "name": "Unique Item IDs", "category": "inventory", "desc": "Every item instance has a unique ID for tracking and save/load."},
		{"id": 1059, "name": "Gold Tracking", "category": "inventory", "desc": "Inventory manager tracks gold separately with add/remove operations."},
		{"id": 1060, "name": "Inventory Save/Load", "category": "inventory", "desc": "Full inventory serialization for save/load support."},

		# --- Inventory UI (#1061-1075) ---
		{"id": 1061, "name": "Inventory Screen", "category": "ui", "desc": "Full inventory screen with equipment panel, item grid, and tooltip."},
		{"id": 1062, "name": "Inventory Toggle (I Key)", "category": "ui", "desc": "Press I to toggle inventory screen open/close."},
		{"id": 1063, "name": "Dark Overlay Background", "category": "ui", "desc": "Inventory screen shows a dark overlay over the game world."},
		{"id": 1064, "name": "Equipment Panel", "category": "ui", "desc": "Left panel shows all 9 equipment slots with current items."},
		{"id": 1065, "name": "8-Column Item Grid", "category": "ui", "desc": "Scrollable 8-column grid displays all inventory items."},
		{"id": 1066, "name": "Sort Buttons Bar", "category": "ui", "desc": "Quick sort buttons above the item grid for rarity/name/type sorting."},
		{"id": 1067, "name": "Item Tooltip Panel", "category": "ui", "desc": "Right panel shows detailed item info on hover."},
		{"id": 1068, "name": "Stat Bonuses Summary", "category": "ui", "desc": "Bottom-right shows total stat bonuses from all equipped items."},
		{"id": 1069, "name": "Gold Display", "category": "ui", "desc": "Current gold amount displayed at the top of inventory."},
		{"id": 1070, "name": "Rarity Color Coding", "category": "ui", "desc": "Item names and borders use rarity-appropriate colors."},
		{"id": 1071, "name": "Click to Equip", "category": "ui", "desc": "Click an equippable item in the grid to equip it instantly."},
		{"id": 1072, "name": "Click to Unequip", "category": "ui", "desc": "Click an equipment slot to unequip the item back to inventory."},
		{"id": 1073, "name": "Click to Use", "category": "ui", "desc": "Click a consumable to use it and apply its effect."},
		{"id": 1074, "name": "Inventory Pauses Game", "category": "ui", "desc": "Opening inventory pauses the game for safe browsing."},
		{"id": 1075, "name": "Close Inventory on ESC", "category": "ui", "desc": "Escape key closes inventory and returns to gameplay."},

		# --- Pause Menu (#1076-1090) ---
		{"id": 1076, "name": "Proper Pause Menu", "category": "ui", "desc": "ESC opens a proper pause menu instead of immediately quitting."},
		{"id": 1077, "name": "Resume Button", "category": "ui", "desc": "Resume button closes pause menu and returns to gameplay."},
		{"id": 1078, "name": "Inventory from Pause", "category": "ui", "desc": "Open inventory directly from the pause menu."},
		{"id": 1079, "name": "Settings Panel", "category": "ui", "desc": "In-game settings accessible from pause menu."},
		{"id": 1080, "name": "Volume Sliders", "category": "ui", "desc": "Master, SFX, and music volume sliders in settings."},
		{"id": 1081, "name": "Camera Zoom Slider", "category": "ui", "desc": "Adjustable camera zoom slider in settings."},
		{"id": 1082, "name": "Shadow Toggle", "category": "ui", "desc": "Toggle shadows on/off in settings for performance."},
		{"id": 1083, "name": "Screen Shake Toggle", "category": "ui", "desc": "Toggle screen shake effects on/off in settings."},
		{"id": 1084, "name": "Auto Pickup Toggle", "category": "ui", "desc": "Toggle auto-pickup behavior in settings."},
		{"id": 1085, "name": "Quit to Menu Button", "category": "ui", "desc": "Quit to main menu button with proper cleanup."},
		{"id": 1086, "name": "Mission Stats Display", "category": "ui", "desc": "Pause menu shows current kills, gold, damage, level, and XP."},
		{"id": 1087, "name": "Random Loading Tip", "category": "ui", "desc": "Pause menu shows a random loading tip at the bottom."},
		{"id": 1088, "name": "Styled Menu Buttons", "category": "ui", "desc": "Pause menu buttons have color-coded styles with hover effects."},
		{"id": 1089, "name": "Settings Back Button", "category": "ui", "desc": "Back button returns from settings to pause menu."},
		{"id": 1090, "name": "Pause Menu Always Processes", "category": "ui", "desc": "Pause menu uses PROCESS_MODE_ALWAYS to work when game is paused."},

		# --- Deployment Flow (#1091-1100) ---
		{"id": 1091, "name": "Starship to Dungeon Transition", "category": "flow", "desc": "Seamless transition from starship to procedural dungeon."},
		{"id": 1092, "name": "Starship Cleanup on Deploy", "category": "flow", "desc": "All starship entities cleaned up when deploying to save memory."},
		{"id": 1093, "name": "Player Preserved on Deploy", "category": "flow", "desc": "Player character, inventory, and stats preserved during deployment."},
		{"id": 1094, "name": "Dungeon Generation on Deploy", "category": "flow", "desc": "Full dungeon procedurally generated when deploying from starship."},
		{"id": 1095, "name": "Deploy Notification", "category": "flow", "desc": "Notification shows 'DEPLOYING TO SURFACE...' during transition."},
		{"id": 1096, "name": "Post-Deploy Tutorial", "category": "flow", "desc": "Tutorial tip appears after landing in the dungeon."},
		{"id": 1097, "name": "Enemy Spawning on Deploy", "category": "flow", "desc": "Initial enemies spawn after deploying to the dungeon."},
		{"id": 1098, "name": "Ambient Change on Deploy", "category": "flow", "desc": "Canvas modulate changes from sci-fi blue to dungeon dark on deploy."},
		{"id": 1099, "name": "Starship Interactable Prompts", "category": "flow", "desc": "[E] prompts appear near interactable objects when player approaches."},
		{"id": 1100, "name": "Loot from Starship Crates", "category": "flow", "desc": "Supply crates in cargo bay give random level-scaled inventory items."},
	]
