# ===== EXTENDED LOADING TIPS (1000 TIPS) =====
# Comprehensive loading tips covering all 1000 improvements

static func get_tips() -> Array[String]:
	var tips: Array[String] = [
		# Original 122 tips (1-122)
		"Dwarves can see in the dark without lights.",
		"Elven BrightEyes attract nature spirits for stronger spells.",
		"Orc Rage builds when taking damage - use it wisely!",
		"Human shields regenerate after a short delay.",
		"Perfect blocks (block within 0.2s of hit) negate all damage.",
		"Mana potions only work on Elves. Dwarves brew them, but cannot use them.",
		"Kill streaks increase your score multiplier up to 5x!",
		"Signs and gravestones contain lore - press E to read them.",
		"Orcs eat their dead to prevent uncontrolled regeneration.",
		"The NecroGenesis activated at 3:47 AM on Day 7.",
		"SafeSpaces are ley line nodes that resist necromantic energy.",
		"Goblins throw rocks at everything. Even friends. It is reflex.",
		"Higher difficulty means more XP and tougher enemies.",
		"Combos increase your damage up to 50% at high hit counts.",
		"Dodge rolling grants brief invincibility frames.",
		"Headshots deal 2x critical damage on humanoid enemies.",
		"Food heals over time - you can eat up to 3 items at once.",
		"The Dwarf Paladin's body cannot be raised as undead.",
		"Lucifer Hades was awake for 200 years on the colony ship.",
		"KillCredits are earned from confirmed combat kills.",
		"Sprinting while attacking extends your melee range.",
		"Charge attacks deal 3x damage but leave you vulnerable.",
		"Bloodlust stacks decay after 5 seconds without a kill.",
		"Fountains in shrine rooms heal you passively.",
		"Altars grant temporary buffs: strength, speed, protection, fury, or life.",
		"Elite enemies glow with a special aura and drop better loot.",
		"Treasure rooms contain enhanced chests with rare items.",
		"Secret rooms are hidden behind breakable walls.",
		"Corridor ambushes can spawn enemies unexpectedly.",
		"Dead-end corridors often contain hidden treasure caches.",
		"Hazard zones deal damage over time - avoid them or resist the element.",
		"Environmental kills count toward your statistics.",
		"Speed running is tracked - try to beat your personal best!",
		"Prestige resets your level but grants permanent bonuses.",
		"Daily challenges refresh every 24 hours with new objectives.",
		"Weapon mastery increases damage with each weapon type.",
		"Revival tokens give you extra lives - use them wisely.",
		"Respawn invulnerability lasts 2 seconds after revival.",
		"Difficulty increases over time during long missions.",
		"Auto-save happens every 60 seconds.",
		"Death recap shows the last 10 damage sources.",
		"Mission time bonuses reward fast completion.",
		"Damage resistance scales with your level.",
		"Critical damage multiplier increases as you level up.",
		"Gold interest earns you passive income every 30 seconds.",
		"Healing efficiency improves with your level.",
		"Damage type resistance helps against elemental attacks.",
		"Lore entries are weighted - new ones spawn more frequently.",
		"Lore collection progress is saved automatically.",
		"Text-to-speech can narrate lore entries if configured.",
		"Emoji sets can be swapped instantly in settings.",
		"Different emoji sets change the entire visual style.",
		"Twemoji renders cleanly at all sizes.",
		"OpenMoji has distinctive black outlines.",
		"Noto Color Emoji is Google's professional set.",
		"Blobmoji has a nostalgic, friendly feel.",
		"Fluent Emoji features 3D-inspired designs.",
		"JoyPixels offers professional polish.",
		"Samsung Emoji has vibrant, bold colors.",
		"System emoji matches your operating system.",
		"Minimap shows room layouts and enemy positions.",
		"Vignette darkens screen edges for atmosphere.",
		"Screen shake intensity can be adjusted.",
		"Camera lead offsets the view toward movement.",
		"Hit markers flash on successful strikes.",
		"Damage numbers float above enemies.",
		"Combo counter escalates with color.",
		"Kill streak announcements celebrate your progress.",
		"Bloodlust display shows your current stacks.",
		"Charge bar indicates attack power buildup.",
		"Boss HP bar appears during major encounters.",
		"DPS meter tracks your damage output.",
		"Gold popups show pickup amounts.",
		"Death screen displays comprehensive statistics.",
		"Tutorial hints can be toggled on or off.",
		"Colorblind mode adjusts colors for accessibility.",
		"Auto-pickup range increases with player level.",
		"Magnet scaling makes items easier to collect.",
		"Item rarity glow indicates value.",
		"Spinning animations help items stand out.",
		"Bobbing animations make items feel alive.",
		"Loot explosion creates satisfying drops.",
		"Gore effects can be disabled for sensitivity.",
		"Blood intensity ranges from off to extreme.",
		"Particle density affects performance.",
		"Shadow quality impacts visual fidelity.",
		"Dynamic lighting creates atmospheric depth.",
		"Hit flash provides impact feedback.",
		"Attack trails show weapon movement.",
		"Impact rings expand on collision.",
		"Ambient particles fill rooms with atmosphere.",
		"Hit pause freezes frames on impact.",
		"Execution slash appears on instant kills.",
		"Charge glow indicates power buildup.",
		"Overkill explosion celebrates massive damage.",
		"Level up burst celebrates progression.",
		"Dodge afterimage shows your movement.",
		"Healing particles indicate recovery.",
		"Shield break shards show protection loss.",
		"Elemental hits use color-coded effects.",
		"Screen flash emphasizes critical moments.",
		"Camera punch provides directional feedback.",
		"Footstep dust shows movement trails.",
		"Ambient mist creates atmospheric rooms.",
		"Sparkles decorate special areas.",
		"Smoke rises from certain decorations.",
		"Water pools slow your movement.",
		"Spike traps deal contact damage.",
		"Poison traps inflict damage over time.",
		"Lightning traps stun on contact.",
		"Ice traps slow movement.",
		"Fire traps burn continuously.",
		"Doors can be opened by approaching.",
		"Buildings contain sidescroller sections.",
		"Platforms require jumping to traverse.",
		"Wall jumps let you reach high areas.",
		"Moving platforms transport you across gaps.",
		"Breakable walls hide secrets.",
		"Spikes in buildings deal damage.",
		"Parallax backgrounds add depth.",
		"Lore pickups bob gently.",
		"Gravestones require E to interact.",
		"Signs display lore when approached.",
		"Crystals sparkle with magical energy.",
		"Tablets contain ancient knowledge.",
		"Journals tell personal stories.",
		"Letters reveal character relationships.",
		"Scrolls hold magical secrets.",
		"Books contain comprehensive lore.",
		"Rare lore entries are harder to find.",
		"Legendary lore is extremely valuable.",
		"Collection UI shows progress per category.",
		"API keys enable text-to-speech.",
		"TTS cache stores generated audio.",
		"Settings persist between sessions.",
		"High score is tracked globally.",
		"Statistics are saved automatically.",
		"Achievements unlock with milestones.",
		
		# Combat & Balance Tips (123-272)
		"Blade ricochet bounces off walls to hit enemies behind obstacles.",
		"Momentum stacking increases damage by 2% per consecutive hit.",
		"Perfect parry within 0.15s triggers automatic counter-attack.",
		"Cleave strikes hit all enemies in a cone in front of you.",
		"Dodge into enemies to trigger spinning slash.",
		"Executioner's edge deals 50% more damage to enemies below 25% HP.",
		"Whirlwind attack hits all surrounding enemies when held.",
		"Armor shatter reduces enemy armor by 5% per consecutive hit.",
		"Lifesteal blade restores 10% of damage dealt as health.",
		"Resonant strike creates shockwave after 3 hits on same enemy.",
		"Piercing shots pass through multiple enemies with reduced damage.",
		"Explosive arrows explode on impact, hitting nearby enemies.",
		"Homing projectiles slightly curve toward nearest enemy.",
		"Rapid fire allows continuous shooting with reduced damage.",
		"Ricochet shots bounce off walls up to 3 times.",
		"Charged shots deal 2x damage when held for 1 second.",
		"Spread shot fires 3 arrows in a spread pattern.",
		"Poison arrows apply poison dealing damage over 5 seconds.",
		"Frost arrows slow enemies by 50% for 3 seconds.",
		"Snapshot accuracy deals 50% more damage after standing still.",
		"Ability chaining costs 25% less mana within 2 seconds.",
		"Cooldown reduction decreases ability cooldowns by 5% per streak.",
		"Ability overcharge deals 50% more damage when used twice.",
		"Mana battery restores 20% mana on melee kills.",
		"Spell echo has 20% chance to trigger ability again for free.",
		"Ability cascade reduces cooldown by 50% on enemy kills.",
		"Mana shield blocks damage by spending mana (1 mana = 1 damage).",
		"Ability amplification increases next ability damage by 10% per cast.",
		"Spell reflection bounces abilities off enemies.",
		"Mana efficiency reduces ability costs by 10% per recent kill.",
		"Damage reduction stacking increases armor by 5% per block.",
		"Reflect damage returns 10% of blocked damage to attacker.",
		"Fortified stance increases armor by 20% while standing still.",
		"Evasion mastery increases dodge chance by 1% per nearby enemy.",
		"Counter attack triggers automatic counter-attack on perfect dodge.",
		"Damage threshold reduces damage below 10% of max HP by 50%.",
		"Invincibility frames grant 0.5s of invulnerability on dodge.",
		"Shield bash stuns nearby enemies when blocking and attacking.",
		"Fortify ability grants 50% damage reduction for 3 seconds.",
		"Damage conversion converts 20% of damage taken to shield.",
		"Poison mastery increases poison damage by 50% for 8 seconds.",
		"Burn mastery makes burning enemies take 25% more damage.",
		"Freeze mastery makes frozen enemies take 50% more melee damage.",
		"Stun mastery makes stunned enemies drop 50% more loot.",
		"Bleed stacking stacks bleed effects for 5% more damage each.",
		"Status effect duration extends all status effects by 25%.",
		"Weakness amplification makes weakened enemies take 30% more damage.",
		"Vulnerability stacking makes vulnerable enemies take 5% more per stack.",
		"Curse mastery makes cursed enemies deal 30% less damage.",
		"Status immunity reduction reduces enemy status resistance by 50%.",
		"Critical cascade increases crit chance by 5% for 5 seconds.",
		"Crit damage scaling increases crit damage by 1% per crit chance.",
		"Guaranteed crit makes every 5th attack guaranteed critical.",
		"Crit heal restores 15% of damage as health on critical hits.",
		"Crit cooldown reduction reduces ability cooldowns by 2s on crits.",
		"Crit mana restore restores 10 mana on critical hits.",
		"Crit knockback knocks enemies back on critical hits.",
		"Crit stun has 30% chance to stun on critical hits.",
		"Crit bleed applies bleed effect on critical hits.",
		"Crit amplification increases next crit damage by 10% per crit.",
		"Combo multiplier increases combo damage multiplier to 75%.",
		"Combo duration extension extends combo timer from 5s to 7s.",
		"Combo finisher triggers massive attack at 10-hit combo.",
		"Combo healing restores 2% max health per combo hit.",
		"Combo mana restores 5 mana per combo hit.",
		"Combo cooldown reduces ability cooldowns by 1s per combo hit.",
		"Combo momentum increases multiplier by 5% per hit.",
		"Combo knockback knocks enemies back slightly with combo hits.",
		"Combo stun stuns all nearby enemies at 10-hit combo.",
		"Combo explosion creates explosion at combo finisher.",
		"Physical damage scaling scales 50% better with strength.",
		"Magical damage scaling scales 50% better with intelligence.",
		"Fire damage scaling increases fire damage by 25%.",
		"Ice damage scaling increases ice damage by 25%.",
		"Lightning damage scaling increases lightning damage by 25%.",
		"Poison damage scaling increases poison damage by 25%.",
		"Holy damage scaling increases holy damage 25%, extra vs undead.",
		"Dark damage scaling increases dark damage 25%, extra vs living.",
		"Elemental synergy increases both elements by 15% when using 2.",
		"Damage type resistance reduction reduces enemy resistances by 25%.",
		"Berserk mode increases damage by 50% at low health.",
		"Glass cannon increases damage by 100% but reduces armor by 50%.",
		"High risk high reward increases damage by 1% per 1% health lost.",
		"Aggressive healing heals 5% of damage dealt.",
		"Momentum damage increases damage by up to 50% when moving.",
		"Stationary damage increases damage by up to 50% when standing still.",
		"Close range damage increases damage by 50% when close to enemies.",
		"Long range damage increases damage by 50% when far from enemies.",
		"Outnumbered strength increases damage by 5% per nearby enemy.",
		"Solo power increases damage by 50% when no allies nearby.",
		"Level scaling increases damage by 5% better per level.",
		"Gear scaling increases damage by 10% better with equipped items.",
		"Stat scaling increases all stats by 25% better with level.",
		"Enemy scaling increases enemy stats by 50% better with difficulty.",
		"Loot scaling increases loot quality by 25% better with level.",
		"XP scaling increases XP gains by 50% better with difficulty.",
		"Health scaling increases max health by 10% per level.",
		"Mana scaling increases max mana by 10% per level.",
		"Stamina scaling increases max stamina by 10% per level.",
		"Armor scaling increases armor by 5% per level.",
		"Stun duration extends stun effects by 25%.",
		"Knockback distance increases knockback by 50%.",
		"Slow duration extends slow effects by 25%.",
		"Root duration extends root effects by 25%.",
		"Crowd control immunity reduces crowd control duration by 25%.",
		"Crowd control resistance reduces enemy crowd control resistance.",
		"Stun chain stuns nearby enemies for 50% duration.",
		"Knockback chain knocks back nearby enemies.",
		"Crowd control amplification increases next effect by 25%.",
		"Crowd control damage makes controlled enemies take 50% more damage.",
		"Mana regeneration increase increases mana regen by 50%.",
		"Stamina regeneration increase increases stamina regen by 50%.",
		"Health regeneration increase increases health regen by 50%.",
		"Resource efficiency reduces all ability costs by 20%.",
		"Resource restoration restores 25% of all resources on kills.",
		"Resource pooling converts unused mana to stamina and vice versa.",
		"Mana battery upgrade restores 50% mana on melee kills.",
		"Stamina battery restores 50% stamina on ranged kills.",
		"Health battery restores 50% health on ability kills.",
		"Resource overflow converts excess resources to damage boost.",
		"Passive damage gain 5% passive damage increase.",
		"Passive defense gain 5% passive damage reduction.",
		"Passive speed gain 10% movement speed increase.",
		"Passive attack speed gain 10% attack speed increase.",
		"Passive crit chance gain 5% crit chance.",
		"Passive dodge chance gain 5% dodge chance.",
		"Passive armor gain 10% armor.",
		"Passive health gain 10% max health.",
		"Passive mana gain 10% max mana.",
		"Passive stamina gain 10% max stamina.",
		"Elemental aura damages nearby enemies.",
		"Thorns damages enemies when hitting you.",
		"Life steal aura grants nearby allies 5% lifesteal.",
		"Damage aura grants nearby allies 10% damage increase.",
		"Defense aura grants nearby allies 10% damage reduction.",
		"Speed aura grants nearby allies 10% movement speed.",
		"Healing aura heals nearby allies 2% max health per second.",
		"Mana aura restores nearby allies 5 mana per second.",
		"Stamina aura restores nearby allies 5 stamina per second.",
		"Blessing aura grants nearby allies random buff every 5 seconds.",
		"Damage amplification chain increases next hit by 5% per hit.",
		"Vulnerability stacking makes enemies take 2% more per hit.",
		"Armor penetration ignores 25% of enemy armor.",
		"Resistance penetration ignores 25% of enemy resistances.",
		"Evasion penetration ignores 25% of enemy evasion.",
		"Block penetration ignores 25% of enemy block chance.",
		"Damage conversion converts 10% of damage taken to boost.",
		"Damage reflection reflects 10% of damage taken.",
		"Damage absorption absorbs 10% of damage dealt as shield.",
		"Damage redistribution damages all nearby enemies by 25%.",
		
		# Enemy AI Tips (273-422)
		"Extended vision range allows enemies to see 50% further.",
		"Peripheral vision lets enemies detect movement in periphery.",
		"Sound detection lets enemies hear loud noises from far away.",
		"Smell detection lets enemies smell player from 2x distance.",
		"Vibration sensing lets enemies sense ground vibrations.",
		"Heat sensing lets enemies detect heat signatures.",
		"Magic detection lets enemies sense magical abilities.",
		"Aura detection lets enemies detect player auras.",
		"Telepathic link shares vision between nearby allies.",
		"Hive mind coordinates attacks between same enemy types.",
		"Flanking AI makes enemies attempt to flank you.",
		"Kiting AI makes ranged enemies maintain distance.",
		"Charging AI makes melee enemies charge at you.",
		"Circling AI makes enemies circle around you.",
		"Ambush AI makes enemies set up ambushes in corridors.",
		"Retreat AI makes enemies retreat when low on health.",
		"Grouping AI makes enemies group together for strength.",
		"Spreading AI makes enemies spread out to avoid AoE.",
		"High ground AI makes enemies seek high ground advantage.",
		"Cover AI makes enemies use cover to reduce damage.",
		"Combo attacks make enemies perform attack combos.",
		"Ability rotation makes enemies rotate through abilities.",
		"Interrupt tactics make enemies interrupt your abilities.",
		"Crowd control tactics make enemies use CC strategically.",
		"Buff stacking makes enemies stack buffs before attacking.",
		"Debuff application makes enemies apply debuffs.",
		"Defensive stance makes enemies take stance when low health.",
		"Aggressive stance makes enemies become aggressive when you're weak.",
		"Tactical retreat makes enemies retreat to heal.",
		"Coordinated attacks make multiple enemies coordinate.",
		"Ability spam makes enemies use abilities more frequently.",
		"Ability chaining makes enemies chain abilities together.",
		"Ability overload makes enemies overload abilities.",
		"Spell reflection makes enemies reflect spells back.",
		"Spell absorption makes enemies absorb spells to heal.",
		"Spell immunity makes enemies gain temporary immunity.",
		"Ability cooldown reduction reduces enemy ability cooldowns.",
		"Ability damage increase makes enemy abilities deal 50% more.",
		"Ability range increase makes enemy abilities have 50% larger range.",
		"Ability AoE increase makes enemy abilities hit 50% larger area.",
		"Damage reduction makes enemies take 25% less damage.",
		"Armor increase gives enemies 50% more armor.",
		"Resistance increase gives enemies 50% more resistances.",
		"Health regeneration makes enemies regenerate 5% health/second.",
		"Damage reflection makes enemies reflect 10% of damage.",
		"Thorns makes enemies deal damage when hit.",
		"Evasion increase gives enemies 50% more evasion.",
		"Block chance makes enemies block 30% of attacks.",
		"Dodge chance makes enemies dodge 30% of attacks.",
		"Invulnerability phases make enemies become invulnerable.",
		"Increased aggression makes enemies 50% more aggressive.",
		"Relentless pursuit makes enemies pursue indefinitely.",
		"Berserk mode makes enemies berserk when low health.",
		"Desperation attacks make desperate enemies use powerful attacks.",
		"Vengeance mode makes enemies stronger after taking damage.",
		"Feeding frenzy makes enemies stronger after kills.",
		"Pack mentality makes enemies stronger when grouped.",
		"Territorial behavior makes enemies defend territory aggressively.",
		"Hunting behavior makes enemies hunt you like prey.",
		"Predatory instinct makes enemies target weak players first.",
		"Damage type adaptation makes enemies adapt to damage types.",
		"Ability adaptation makes enemies adapt to abilities.",
		"Playstyle adaptation makes enemies adapt to playstyle.",
		"Weakness learning makes enemies learn your weaknesses.",
		"Strategy learning makes enemies learn from encounters.",
		"Resistance building makes enemies build resistance.",
		"Counter strategy makes enemies develop counters.",
		"Tactical evolution makes enemies evolve tactics.",
		"Intelligent retreat makes enemies retreat when outmatched.",
		"Calculated risk makes enemies take calculated risks.",
		"Increased spawn rate makes enemies spawn 50% more frequently.",
		"Spawn waves makes enemies spawn in coordinated waves.",
		"Elite spawning makes elite enemies spawn more frequently.",
		"Boss spawning makes boss enemies spawn more frequently.",
		"Reinforcement spawning makes enemies call for reinforcements.",
		"Level scaling makes enemies scale with player level.",
		"Difficulty scaling makes enemies scale with difficulty.",
		"Stat scaling makes enemy stats scale 50% better.",
		"Ability scaling makes enemy abilities scale with level.",
		"Loot scaling makes enemy loot scale with level.",
		"Type synergy gives same enemy types bonuses together.",
		"Damage synergy makes enemies amplify each other's damage.",
		"Defense synergy makes enemies amplify each other's defense.",
		"Ability synergy makes enemies combine abilities.",
		"Buff sharing makes enemies share buffs with allies.",
		"Healing synergy makes enemies heal each other.",
		"Damage sharing makes enemies share damage taken.",
		"Resurrection synergy makes enemies resurrect fallen allies.",
		"Empowerment aura makes enemies empower nearby allies.",
		"Corruption aura makes enemies corrupt nearby allies.",
		"Shield mechanics give enemies regenerating shields.",
		"Armor mechanics give enemies layered armor.",
		"Phase mechanics make enemies phase between dimensions.",
		"Splitting mechanics make enemies split into smaller versions.",
		"Merging mechanics make enemies merge into stronger forms.",
		"Transformation mechanics make enemies transform when low health.",
		"Possession mechanics make enemies possess other enemies.",
		"Cloning mechanics make enemies create clones.",
		"Summoning mechanics make enemies summon minions.",
		"Corruption mechanics make enemies corrupt environment.",
		"Elemental weakness gives enemies elemental weaknesses.",
		"Type weakness gives enemies weakness to damage types.",
		"Status weakness makes enemies vulnerable to status effects.",
		"Ability weakness makes enemies weak to certain abilities.",
		"Playstyle weakness makes enemies weak to playstyles.",
		"Positional weakness makes enemies weak from positions.",
		"Timing weakness makes enemies vulnerable at times.",
		"Resource weakness makes enemies weak when low resources.",
		"Isolated weakness makes enemies weak when isolated.",
		"Outnumbered weakness makes enemies weak when outnumbered.",
		"Increased loot drop makes enemies drop 50% more loot.",
		"Rare loot increase makes enemies drop 50% more rare loot.",
		"Gold drop increase makes enemies drop 50% more gold.",
		"XP drop increase makes enemies give 50% more XP.",
		"Artifact drops make enemies drop artifacts.",
		"Unique drops make enemies drop unique items.",
		"Crafting material drops make enemies drop materials.",
		"Currency drops make enemies drop special currency.",
		"Consumable drops make enemies drop consumables.",
		"Buff drops make enemies drop temporary buffs.",
		"Damage multiplier multiplies enemy damage by 1.5x.",
		"Health multiplier multiplies enemy health by 1.5x.",
		"Speed multiplier multiplies enemy speed by 1.5x.",
		"Ability frequency makes enemies use abilities 50% more.",
		"Attack frequency makes enemies attack 50% more.",
		"Spawn frequency makes enemies spawn 50% more.",
		"Reinforcement frequency makes enemies call reinforcements more.",
		"Buff frequency makes enemies buff themselves more.",
		"Debuff frequency makes enemies debuff you more.",
		"Crowd control frequency makes enemies use CC more.",
		"Coordinated attacks make enemies coordinate perfectly.",
		"Synchronized abilities make enemies synchronize abilities.",
		"Formation fighting makes enemies maintain formations.",
		"Pincer movement makes enemies execute pincer movements.",
		"Encirclement makes enemies attempt to encircle you.",
		"Distraction tactics make enemies distract while others attack.",
		"Support tactics make enemies support each other.",
		"Sacrifice tactics make enemies sacrifice for advantage.",
		"Bait tactics make enemies use bait to lure you.",
		"Trap tactics make enemies set traps for you.",
		"Mutation system makes enemies mutate during combat.",
		"Evolution system makes enemies evolve into stronger forms.",
		"Corruption system makes enemies corrupt each other.",
		"Fusion system makes enemies fuse into mega enemies.",
		"Parasitic system makes enemies parasitize each other.",
		"Symbiosis system makes enemies form symbiotic bonds.",
		"Hivemind system makes enemies form collective hivemind.",
		"Consciousness transfer makes enemies transfer consciousness.",
		"Dimensional anchoring makes enemies anchor to dimensions.",
		"Reality warping makes enemies warp reality.",
		
		# Items & Loot Tips (423-572)
		"Weapon damage scaling makes weapons scale 50% better.",
		"Weapon rarity increase makes weapons drop at higher rarity.",
		"Weapon enchantment lets weapons be enchanted with effects.",
		"Weapon evolution makes weapons evolve into stronger forms.",
		"Weapon fusion combines weapons for stronger versions.",
		"Weapon transmutation transforms weapons into other types.",
		"Weapon augmentation augments weapons with properties.",
		"Weapon mastery bonus grants 50% more mastery bonus.",
		"Weapon synergy grants bonus for dual wielding same type.",
		"Weapon resonance makes weapons resonate together.",
		"Armor defense scaling makes armor scale 50% better.",
		"Armor rarity increase makes armor drop at higher rarity.",
		"Armor enchantment lets armor be enchanted with effects.",
		"Armor evolution makes armor evolve into stronger forms.",
		"Armor set bonuses grants powerful bonus for full set.",
		"Armor transmutation transforms armor into other types.",
		"Armor augmentation augments armor with properties.",
		"Armor durability makes armor last 50% longer.",
		"Armor regeneration makes armor regenerate durability.",
		"Armor resonance makes full set resonate for power.",
		"Ring slots gain additional ring slots.",
		"Amulet slots gain additional amulet slots.",
		"Trinket slots gain additional trinket slots.",
		"Accessory scaling makes accessories scale 50% better.",
		"Accessory rarity makes accessories drop at higher rarity.",
		"Accessory stacking makes effects stack multiplicatively.",
		"Accessory synergy grants bonuses for matching accessories.",
		"Accessory evolution makes accessories evolve.",
		"Accessory fusion combines accessories for power.",
		"Accessory transmutation transforms accessories.",
		"Potion effectiveness makes potions 50% more effective.",
		"Potion duration extends potion effects by 50%.",
		"Potion stacking makes potion effects stack.",
		"Potion crafting lets you craft potions from materials.",
		"Potion transmutation converts potions into other types.",
		"Food healing makes food heal 50% more.",
		"Food buffs makes food grant temporary buffs.",
		"Food stacking makes food effects stack.",
		"Consumable efficiency reduces consumable costs by 50%.",
		"Consumable crafting lets you craft consumables.",
		"Loot rarity increase makes all loot drop at higher rarity.",
		"Legendary loot chance makes legendary items drop 50% more.",
		"Epic loot chance makes epic items drop 50% more.",
		"Rare loot chance makes rare items drop 50% more.",
		"Loot quality scaling makes loot quality scale with level.",
		"Loot stat scaling makes loot stats scale 50% better.",
		"Loot enchantment chance makes loot drop pre-enchanted.",
		"Loot perfection makes loot drop with perfect stats.",
		"Loot duplication chance to duplicate loot drops.",
		"Loot multiplication multiplies loot drops by 1.5x.",
		"Gold drop increase makes enemies drop 50% more gold.",
		"Gold multiplier multiplies all gold gains by 1.5x.",
		"Gold interest makes gold earn interest over time.",
		"Gold conversion converts gold to other currencies.",
		"Gold duplication chance to duplicate gold drops.",
		"Currency conversion converts between currencies freely.",
		"Currency stacking makes currencies stack for bonuses.",
		"Currency scaling makes currency values scale with level.",
		"Treasure hunting finds hidden treasure caches.",
		"Wealth generation generates passive wealth over time.",
		"Crafting recipes unlocks new crafting recipes.",
		"Crafting efficiency reduces crafting costs by 50%.",
		"Crafting speed makes crafting 50% faster.",
		"Crafting quality makes crafted items higher quality.",
		"Enchanting recipes unlocks new enchanting recipes.",
		"Enchanting efficiency reduces enchanting costs by 50%.",
		"Enchanting success rate increases success by 50%.",
		"Enchanting power makes enchantments 50% more powerful.",
		"Disenchanting lets you disenchant items.",
		"Transmutation lets you transmute items.",
		"Stat scaling makes item stats scale 50% better.",
		"Stat perfection makes items drop with perfect stats.",
		"Stat stacking makes item stats stack multiplicatively.",
		"Stat synergy grants bonuses for matching stats.",
		"Stat conversion converts between different stats.",
		"Stat multiplication multiplies item stats by 1.5x.",
		"Stat duplication chance to duplicate item stats.",
		"Stat rerolling lets you reroll item stats.",
		"Stat optimization automatically optimizes item stats.",
		"Stat augmentation augments items with extra stats.",
		"Durability increase makes items last 50% longer.",
		"Durability regeneration makes items regenerate durability.",
		"Durability repair lets you repair items.",
		"Durability scaling makes durability scale with level.",
		"Indestructible items makes items never break.",
		"Self-repairing items makes items repair automatically.",
		"Durability sharing makes items share durability.",
		"Durability pooling pools durability across items.",
		"Durability conversion converts durability to damage.",
		"Durability immunity ignores durability penalties.",
		"Item identification identifies items to reveal stats.",
		"Item appraisal appraises items to find value.",
		"Item grading grades items by quality.",
		"Item certification certifies items for bonuses.",
		"Item authentication authenticates items for value.",
		"Item valuation automatically values items.",
		"Item comparison compares items side-by-side.",
		"Item recommendations gets item recommendations.",
		"Item tracking tracks item locations.",
		"Item organization organizes items automatically.",
		"Unique item drops makes unique items drop more.",
		"Legendary item drops makes legendary items drop more.",
		"Mythic item drops makes mythic items drop occasionally.",
		"Artifact item drops makes artifact items drop occasionally.",
		"Divine item drops makes divine items drop occasionally.",
		"Cursed item drops makes cursed items drop with effects.",
		"Blessed item drops makes blessed items drop with bonuses.",
		"Soulbound items makes items bind to player for power.",
		"Sentient items makes items gain sentience.",
		"Evolving items makes items evolve as you use them.",
		"Item set bonuses grants bonuses for wearing sets.",
		"Item set synergy makes sets synergize for power.",
		"Item collection bonuses grants bonuses for collections.",
		"Item collection tracking tracks item collections.",
		"Item collection rewards completes collections for rewards.",
		"Item transmutation sets transmutes full sets.",
		"Item fusion sets fuses sets into mega items.",
		"Item evolution sets makes sets evolve.",
		"Item resonance sets makes sets resonate.",
		"Item harmony sets makes sets achieve harmony.",
		"Inventory expansion increases inventory size by 50%.",
		"Inventory organization organizes inventory automatically.",
		"Inventory sorting sorts inventory by criteria.",
		"Inventory filtering filters inventory by type.",
		"Inventory search searches inventory for items.",
		"Storage expansion expands storage capacity.",
		"Storage organization organizes storage automatically.",
		"Item stacking stacks items for space efficiency.",
		"Dimensional storage stores items in pocket dimension.",
		"Infinite storage accesses infinite storage space.",
		"Item trading trades items with NPCs.",
		"Item selling sells items for better prices.",
		"Item buying buys items from merchants.",
		"Item auctions auctions items to highest bidder.",
		"Item bartering barters items for other items.",
		"Item gifting gifts items to other players.",
		"Item sharing shares items with party members.",
		"Item lending lends items temporarily.",
		"Item insurance insures items against loss.",
		"Item valuation automatically values items fairly.",
		"Item mutation mutates items into new forms.",
		"Item evolution evolves items as you use them.",
		"Item corruption corrupts items for dark power.",
		"Item purification purifies corrupted items.",
		"Item fusion fuses items together.",
		"Item splitting splits items into components.",
		"Item cloning clones items for duplicates.",
		"Item transmutation transmutes items into others.",
		"Item resurrection resurrects destroyed items.",
		"Item ascension ascends items to higher tiers.",
		
		# Map & Dungeon Tips (573-722)
		"Room variety increases variety in room layouts.",
		"Room complexity makes rooms have more complex layouts.",
		"Room decoration decorates rooms with more details.",
		"Room theming gives rooms distinct themes.",
		"Room scaling makes rooms scale with difficulty.",
		"Room density makes rooms have more content.",
		"Room connections makes rooms connect interestingly.",
		"Room secrets makes rooms contain more secrets.",
		"Room hazards makes rooms contain environmental hazards.",
		"Room treasures makes rooms contain treasure caches.",
		"Corridor variety gives corridors varied designs.",
		"Corridor complexity makes corridors have complex layouts.",
		"Corridor decoration decorates corridors with details.",
		"Corridor ambushes makes corridors contain ambush points.",
		"Corridor hazards makes corridors contain hazards.",
		"Corridor secrets makes corridors contain secrets.",
		"Corridor treasures makes corridors contain treasures.",
		"Corridor traps makes corridors contain traps.",
		"Corridor lighting gives corridors dynamic lighting.",
		"Corridor atmosphere gives corridors atmospheric effects.",
		"Crypt theme allows dungeons to be crypts.",
		"Castle theme allows dungeons to be castles.",
		"Cave theme allows dungeons to be caves.",
		"Temple theme allows dungeons to be temples.",
		"Laboratory theme allows dungeons to be laboratories.",
		"Prison theme allows dungeons to be prisons.",
		"Mansion theme allows dungeons to be mansions.",
		"Sewers theme allows dungeons to be sewers.",
		"Mines theme allows dungeons to be mines.",
		"Forest theme allows dungeons to be forests.",
		"Lava pits makes dungeons contain lava pits.",
		"Water features makes dungeons contain water features.",
		"Bridges makes dungeons contain bridges.",
		"Platforms makes dungeons contain platforms.",
		"Pillars makes dungeons contain pillars.",
		"Statues makes dungeons contain statues.",
		"Altars makes dungeons contain altars.",
		"Fountains makes dungeons contain fountains.",
		"Doors makes dungeons contain locked doors.",
		"Gates makes dungeons contain gates.",
		"Spike traps makes dungeons contain spike traps.",
		"Poison gas makes dungeons contain poison gas.",
		"Fire traps makes dungeons contain fire traps.",
		"Ice traps makes dungeons contain ice traps.",
		"Lightning traps makes dungeons contain lightning traps.",
		"Falling objects makes dungeons have falling objects.",
		"Crumbling floors makes dungeons have crumbling floors.",
		"Collapsing ceilings makes dungeons have collapsing ceilings.",
		"Moving walls makes dungeons have moving walls.",
		"Rotating platforms makes dungeons have rotating platforms.",
		"Hidden rooms makes dungeons contain hidden rooms.",
		"Secret passages makes dungeons contain secret passages.",
		"Hidden treasures makes dungeons contain hidden treasures.",
		"Secret doors makes dungeons contain secret doors.",
		"Hidden switches makes dungeons contain hidden switches.",
		"Concealed chests makes dungeons contain concealed chests.",
		"Hidden altars makes dungeons contain hidden altars.",
		"Secret shrines makes dungeons contain secret shrines.",
		"Hidden vaults makes dungeons contain hidden vaults.",
		"Secret chambers makes dungeons contain secret chambers.",
		"Boss arena design gives boss arenas unique designs.",
		"Boss arena hazards makes boss arenas contain hazards.",
		"Boss arena mechanics gives boss arenas special mechanics.",
		"Boss arena scaling makes boss arenas scale with difficulty.",
		"Boss arena phases makes boss arenas change during fight.",
		"Boss arena minions makes boss arenas spawn minions.",
		"Boss arena traps makes boss arenas contain traps.",
		"Boss arena pillars makes boss arenas have destructible pillars.",
		"Boss arena platforms makes boss arenas have moving platforms.",
		"Boss arena atmosphere gives boss arenas atmospheric effects.",
		"Seed-based generation generates dungeons from seeds.",
		"Perlin noise generation uses Perlin noise for generation.",
		"Cellular automata uses cellular automata for caves.",
		"Recursive generation uses recursive dungeon generation.",
		"Constraint-based generation generates with constraints.",
		"Graph-based generation generates using graphs.",
		"Template-based generation generates from templates.",
		"Hybrid generation combines multiple generation methods.",
		"Adaptive generation makes generation adapt to player.",
		"Dynamic generation makes dungeons generate dynamically.",
		"Difficulty scaling makes dungeons scale with difficulty.",
		"Enemy density scaling makes enemy density scale.",
		"Hazard scaling makes hazards scale with difficulty.",
		"Trap scaling makes traps scale with difficulty.",
		"Loot scaling makes loot scale with difficulty.",
		"Boss scaling makes bosses scale with difficulty.",
		"Complexity scaling makes complexity scale.",
		"Density scaling makes density scale with difficulty.",
		"Variety scaling makes variety scale with difficulty.",
		"Challenge scaling makes challenge scale.",
		"Linear progression gives dungeons linear progression.",
		"Branching progression gives dungeons branching paths.",
		"Non-linear progression makes dungeons non-linear.",
		"Hub-based progression makes dungeons use hub system.",
		"Gated progression gates progression by keys/abilities.",
		"Vertical progression gives dungeons vertical levels.",
		"Horizontal progression makes dungeons expand horizontally.",
		"Spiral progression makes dungeons spiral downward.",
		"Circular progression makes dungeons form circles.",
		"Maze progression makes dungeons be mazes.",
		"Lighting system provides dynamic lighting.",
		"Fog effects provides fog effects.",
		"Particle effects provides particle effects.",
		"Sound design provides atmospheric sounds.",
		"Music system provides dynamic music.",
		"Color grading provides color grading.",
		"Ambient effects provides ambient effects.",
		"Environmental storytelling tells story through environment.",
		"Visual themes provides distinct visual themes.",
		"Immersion effects provides immersion effects.",
		"Treasure rooms makes dungeons contain treasure rooms.",
		"Loot caches makes dungeons contain loot caches.",
		"Artifact rooms makes dungeons contain artifact rooms.",
		"Vault rooms makes dungeons contain vault rooms.",
		"Reward scaling makes rewards scale with difficulty.",
		"Bonus rewards grants bonus rewards for completion.",
		"Challenge rewards grants rewards for challenges.",
		"Speed rewards grants rewards for speed completion.",
		"Perfection rewards grants rewards for perfect runs.",
		"Discovery rewards grants rewards for discoveries.",
		"Random events provides random events.",
		"Triggered events provides events triggered by actions.",
		"Timed events provides events triggered by time.",
		"Cascading events makes events trigger other events.",
		"Earthquake events provides earthquakes.",
		"Collapse events provides collapses.",
		"Flood events provides floods.",
		"Fire events provides fires.",
		"Invasion events provides enemy invasions.",
		"Corruption events makes corruption spread.",
		"Persistent dungeons makes dungeons persist between visits.",
		"Dynamic changes makes dungeons change over time.",
		"Player impact makes player actions affect dungeons.",
		"Destruction persistence makes destroyed objects stay destroyed.",
		"Enemy persistence makes killed enemies stay dead.",
		"Loot persistence makes taken loot stay taken.",
		"State tracking tracks dungeon state.",
		"Progress tracking tracks player progress.",
		"Completion tracking tracks dungeon completion.",
		"Statistics tracking tracks dungeon statistics.",
		"Dungeon corruption makes dungeons become corrupted.",
		"Dungeon evolution makes dungeons evolve over time.",
		"Dungeon mutation makes dungeons mutate randomly.",
		"Dungeon fusion makes dungeons fuse together.",
		"Dungeon splitting makes dungeons split into sections.",
		"Dungeon merging makes dungeons merge with others.",
		"Dungeon transformation makes dungeons transform completely.",
		"Dungeon ascension makes dungeons ascend to higher tiers.",
		"Dungeon recursion makes dungeons contain dungeons.",
		"Dungeon infinity provides infinite dungeon generation.",
		
		# UI/UX Tips (723-872)
		"Health bar displays health bar with animations.",
		"Mana bar displays mana bar with animations.",
		"Stamina bar displays stamina bar with animations.",
		"Experience bar displays experience bar.",
		"Combo counter displays combo counter.",
		"Kill streak counter displays kill streak counter.",
		"Damage numbers displays floating damage numbers.",
		"Healing numbers displays floating healing numbers.",
		"Critical hit indicator indicates critical hits.",
		"Status effect icons displays status effect icons.",
		"Minimap displays minimap of current area.",
		"Full map displays full dungeon map.",
		"Map markers marks important locations on map.",
		"Waypoints lets you set and navigate to waypoints.",
		"Compass displays compass for direction.",
		"Coordinates displays player coordinates.",
		"Distance indicator shows distance to objectives.",
		"Direction indicator shows direction to objectives.",
		"Fog of war reveals map as you explore.",
		"Map zoom lets you zoom in/out on map.",
		"Inventory display displays inventory grid.",
		"Equipment display displays equipped items.",
		"Item tooltips shows item details on hover.",
		"Item comparison compares items side-by-side.",
		"Item sorting sorts inventory by criteria.",
		"Item filtering filters inventory by type.",
		"Item search searches inventory for items.",
		"Item rarity colors colors items by rarity.",
		"Item icons displays item icons.",
		"Item stacking stacks items in inventory.",
		"Character sheet displays detailed character stats.",
		"Stat tooltips shows stat details on hover.",
		"Stat comparisons compares stats with items.",
		"Stat tracking tracks stat changes over time.",
		"Attribute display displays character attributes.",
		"Skill display displays learned skills.",
		"Ability display displays available abilities.",
		"Talent display displays talent tree.",
		"Perk display displays active perks.",
		"Buff display displays active buffs.",
		"Ability hotbar displays ability hotbar.",
		"Ability cooldown shows ability cooldowns.",
		"Ability tooltips shows ability details on hover.",
		"Ability keybinds displays ability keybinds.",
		"Ability descriptions displays ability descriptions.",
		"Skill tree displays skill tree interface.",
		"Talent tree displays talent tree interface.",
		"Perk selection lets you select perks.",
		"Ability customization lets you customize loadouts.",
		"Hotkey configuration lets you configure hotkeys.",
		"Quest log displays quest log.",
		"Quest markers marks quest objectives on map.",
		"Quest tracker tracks active quests.",
		"Objective list displays current objectives.",
		"Progress tracking tracks quest progress.",
		"Reward preview previews quest rewards.",
		"Quest descriptions displays quest descriptions.",
		"Quest history tracks completed quests.",
		"Objective markers marks objectives in world.",
		"Compass objectives shows objectives on compass.",
		"Enemy health bars displays enemy health bars.",
		"Boss health bar displays boss health bar prominently.",
		"Enemy names displays enemy names above them.",
		"Threat indicator shows threat level indicator.",
		"Aggro indicator shows enemy aggro status.",
		"Hit markers shows hit markers on screen.",
		"Critical hit flash flashes on critical hits.",
		"Dodge indicator indicates successful dodges.",
		"Block indicator indicates successful blocks.",
		"Parry indicator indicates successful parries.",
		"Resource bars displays all resource bars.",
		"Resource numbers displays resource amounts.",
		"Resource regeneration shows resource regen rate.",
		"Resource warnings warns when resources low.",
		"Resource efficiency shows resource efficiency.",
		"Resource conversion shows resource conversions.",
		"Resource pooling shows resource pools.",
		"Resource overflow shows resource overflow.",
		"Resource tracking tracks resource changes.",
		"Resource predictions predicts resource changes.",
		"Damage notifications notifies on damage taken.",
		"Healing notifications notifies on healing received.",
		"Level up notifications notifies on level up.",
		"Achievement notifications notifies on achievements.",
		"Loot notifications notifies on loot drops.",
		"Status notifications notifies on status effects.",
		"Ability notifications notifies on ability ready.",
		"Quest notifications notifies on quest updates.",
		"System notifications notifies on system events.",
		"Custom notifications creates custom notifications.",
		"Graphics settings configures graphics options.",
		"Audio settings configures audio options.",
		"Gameplay settings configures gameplay options.",
		"Control settings configures control options.",
		"UI settings configures UI options.",
		"Accessibility settings configures accessibility options.",
		"Language settings configures language options.",
		"Keybind configuration configures keybinds.",
		"Settings profiles saves settings profiles.",
		"Settings reset resets settings to default.",
		"Main menu provides main menu interface.",
		"Pause menu provides pause menu interface.",
		"Settings menu provides settings menu interface.",
		"Character menu provides character menu interface.",
		"Inventory menu provides inventory menu interface.",
		"Map menu provides map menu interface.",
		"Quest menu provides quest menu interface.",
		"Achievement menu provides achievement menu interface.",
		"Statistics menu provides statistics menu interface.",
		"Help menu provides help menu interface.",
		"Screen flash flashes screen on events.",
		"Screen shake shakes screen on impact.",
		"Screen blur blurs screen effect.",
		"Screen vignette provides vignette effect.",
		"Color grading provides color grading effects.",
		"Particle effects provides particle effects in UI.",
		"Transition effects provides transition effects.",
		"Animation effects provides animation effects in UI.",
		"Glow effects provides glow effects on UI elements.",
		"Shadow effects provides shadow effects on UI elements.",
		"Font selection selects from multiple fonts.",
		"Font sizing adjusts font sizes.",
		"Text localization localizes text to languages.",
		"Text formatting formats text with colors/styles.",
		"Text shadows adds shadows to text.",
		"Text outlines adds outlines to text.",
		"Text scaling scales text with resolution.",
		"Text readability improves text readability.",
		"Text animations animates text elements.",
		"Text tooltips shows tooltips for text.",
		"Colorblind mode provides colorblind friendly colors.",
		"High contrast mode provides high contrast UI mode.",
		"Screen reader support supports screen readers.",
		"Text-to-speech provides text-to-speech narration.",
		"Closed captions displays closed captions.",
		"Subtitle display displays subtitles.",
		"Font size adjustment adjusts font sizes.",
		"UI scaling scales entire UI.",
		"Controller support provides full controller support.",
		"Customizable controls provides fully customizable controls.",
		"Draggable windows lets you drag UI windows.",
		"Resizable windows lets you resize UI windows.",
		"Window docking lets you dock windows together.",
		"Window tabs lets you tab between windows.",
		"UI customization lets you customize UI layout.",
		"UI themes lets you select UI themes.",
		"UI opacity lets you adjust UI opacity.",
		"UI positioning lets you reposition UI elements.",
		"UI anchoring lets you anchor UI to screen edges.",
		"UI layering lets you layer UI elements.",
		
		# Quality of Life Tips (873-1000)
		"LOD system provides level of detail rendering.",
		"Culling system provides frustum culling.",
		"Batching system provides batch rendering.",
		"Memory optimization optimizes memory usage.",
		"CPU optimization optimizes CPU usage.",
		"GPU optimization optimizes GPU usage.",
		"Asset streaming streams assets dynamically.",
		"Lazy loading loads assets on demand.",
		"Caching system caches frequently used assets.",
		"Compression compresses assets for efficiency.",
		"Loading screen displays loading screen.",
		"Loading bar shows loading progress bar.",
		"Loading tips displays tips while loading.",
		"Fast loading optimizes loading speed.",
		"Seamless loading loads without interruption.",
		"Background loading loads in background.",
		"Transition effects provides smooth transition effects.",
		"Fade transitions provides fade in/out transitions.",
		"Slide transitions provides slide transitions.",
		"Dissolve transitions provides dissolve transitions.",
		"Auto-save automatically saves progress.",
		"Quick save provides quick save functionality.",
		"Quick load provides quick load functionality.",
		"Multiple saves supports multiple save files.",
		"Save slots organizes saves in slots.",
		"Save backup backs up save files.",
		"Save encryption encrypts save files.",
		"Save compression compresses save files.",
		"Cloud saves saves to cloud storage.",
		"Cross-platform saves syncs saves across platforms.",
		"Keyboard support provides full keyboard support.",
		"Mouse support provides full mouse support.",
		"Controller support provides full controller support.",
		"Touch support provides touch screen support.",
		"Gamepad rumble provides gamepad rumble feedback.",
		"Haptic feedback provides haptic feedback on devices.",
		"Input buffering buffers inputs for responsiveness.",
		"Input remapping remaps input controls.",
		"Input profiles saves input profiles.",
		"Input sensitivity adjusts input sensitivity.",
		"Master volume controls master volume.",
		"Music volume controls music volume.",
		"SFX volume controls sound effect volume.",
		"Voice volume controls voice volume.",
		"Audio mixing mixes audio channels.",
		"Spatial audio provides 3D spatial audio.",
		"Audio compression compresses audio files.",
		"Audio streaming streams audio dynamically.",
		"Audio caching caches audio files.",
		"Audio synchronization syncs audio with gameplay.",
		"Resolution scaling scales resolution dynamically.",
		"Frame rate limiting limits frame rate.",
		"VSync support supports vertical sync.",
		"Anti-aliasing provides anti-aliasing options.",
		"Texture filtering provides texture filtering options.",
		"Shadow quality adjusts shadow quality.",
		"Lighting quality adjusts lighting quality.",
		"Particle quality adjusts particle quality.",
		"Effect quality adjusts effect quality.",
		"Overall quality provides overall graphics quality setting.",
		"Difficulty assist provides assist mode for difficulty.",
		"Invincibility mode toggles invincibility.",
		"Infinite resources toggles infinite resources.",
		"One-hit kill toggles one-hit kills.",
		"Slow motion toggles slow motion mode.",
		"Fast forward toggles fast forward mode.",
		"Pause anywhere lets you pause game anywhere.",
		"Rewind gameplay lets you rewind gameplay.",
		"Skip cutscenes lets you skip cutscenes.",
		"Skip animations lets you skip animations.",
		"Tutorial mode provides interactive tutorial mode.",
		"Contextual help provides context-sensitive help.",
		"Tooltips provides hover tooltips for help.",
		"Help system provides comprehensive help system.",
		"Video tutorials provides video tutorials.",
		"Text guides provides text-based guides.",
		"Interactive guides provides interactive guides.",
		"FAQ system provides FAQ database.",
		"Search help lets you search help topics.",
		"Feedback system lets you send feedback in-game.",
		"Play time tracking tracks total play time.",
		"Kill tracking tracks total kills.",
		"Death tracking tracks total deaths.",
		"Damage tracking tracks total damage dealt.",
		"Healing tracking tracks total healing.",
		"Gold tracking tracks gold earned.",
		"XP tracking tracks XP earned.",
		"Loot tracking tracks items found.",
		"Achievement tracking tracks achievements.",
		"Statistics dashboard views all statistics.",
		"Character customization customizes character appearance.",
		"UI customization customizes UI layout.",
		"Color customization customizes colors.",
		"Theme customization customizes themes.",
		"Hotbar customization customizes hotbars.",
		"Loadout customization customizes loadouts.",
		"Keybind customization customizes keybinds.",
		"Control customization customizes controls.",
		"Preset customization saves customization presets.",
		"Profile management manages player profiles.",
		"Leaderboards provides global leaderboards.",
		"Friend list adds and manages friends.",
		"Party system forms parties with friends.",
		"Chat system provides in-game chat.",
		"Voice chat provides voice communication.",
		"Guilds lets you join guilds.",
		"Guild chat provides guild communication.",
		"Clan system lets you form clans.",
		"Trading system lets you trade with players.",
		"Messaging system lets you send messages.",
		"Battle pass provides seasonal battle pass.",
		"Reward tiers provides tier-based rewards.",
		"Daily rewards provides daily login rewards.",
		"Weekly rewards provides weekly challenge rewards.",
		"Monthly rewards provides monthly milestone rewards.",
		"Seasonal rewards provides seasonal rewards.",
		"Milestone rewards provides milestone-based rewards.",
		"Achievement rewards provides achievement rewards.",
		"Challenge rewards provides challenge completion rewards.",
		"Prestige rewards provides prestige system rewards.",
		"Limited events provides time-limited events.",
		"Seasonal events provides seasonal events.",
		"Holiday events provides holiday-themed events.",
		"Special events provides special events.",
		"Community events provides community-driven events.",
		"Event rewards provides exclusive event rewards.",
		"Event challenges provides event-specific challenges.",
		"Event quests provides event-specific quests.",
		"Event dungeons provides event-specific dungeons.",
		"Event shop provides event-specific shop.",
		"Animation polish polishes all animations.",
		"Visual polish polishes visual effects.",
		"Audio polish polishes sound design.",
		"UI polish polishes user interface.",
		"Gameplay polish polishes gameplay mechanics.",
		"Particle polish polishes particle effects.",
		"Lighting polish polishes lighting system.",
		"Shader polish polishes shader effects.",
		"Performance polish polishes performance.",
		"Overall polish provides overall game polish.",
		"New game plus provides New Game Plus mode.",
		"Hardcore mode provides hardcore difficulty mode.",
		"Sandbox mode provides sandbox/creative mode.",
		"Challenge modes provides special challenge modes.",
		"Endless mode provides endless dungeon mode.",
		"Time attack mode provides time attack mode.",
		"Survival mode provides survival mode.",
		"Custom difficulty lets you create custom difficulties.",
		"Modding support supports game mods.",
		"Community content supports community content.",
	]
	return tips
