-- lobby_generator.lua (REWRITE)
-- Builds the spaceship exterior lobby + landing pad + dungeon portal.
-- Spaceship is generated by spaceship_builder.lua.
-- Dungeon is at Z=2000; lobby is at Z=0.

local SpaceshipBuilder   = require(script.Parent:WaitForChild("spaceship_builder"))
local LobbyFurnitureGenerator = require(script.Parent:WaitForChild("lobby_furniture_generator"))
local LobbyBookGenerator = require(script.Parent:WaitForChild("lobby_book_generator"))

local LobbyGenerator = {}
LobbyGenerator.__index = LobbyGenerator

-- Lobby is centred at origin, floating ~14 studs up (struts land at Y=0)
local SHIP_Y = 30

function LobbyGenerator.new(parent)
	local self = setmetatable({}, LobbyGenerator)
	self.parent = parent or workspace
	return self
end

function LobbyGenerator:generateLobby()
	local existing = self.parent:FindFirstChild("Lobby")
	if existing then existing:Destroy() end

	local lobbyFolder = Instance.new("Folder")
	lobbyFolder.Name  = "Lobby"
	lobbyFolder.Parent = self.parent

	-- Build the saucer (floats so struts sit at Y=0)
	SpaceshipBuilder.build(lobbyFolder, Vector3.new(0, SHIP_Y, 0))

	-- Flat landing pad on the ground below the ship
	self:buildLandingPad(lobbyFolder)

	-- Interior deck (walkable surface inside the saucer hull)
	self:buildInteriorDeck(lobbyFolder)

	-- Add SpawnLocation on the deck (Inside the ship)
	local spawn = Instance.new("SpawnLocation")
	spawn.Name = "LobbySpawn"
	spawn.Size = Vector3.new(10, 1, 10)
	spawn.Anchored = true
	spawn.Transparency = 1
	spawn.CanCollide = true
	spawn.Duration = 0
	spawn.CFrame = CFrame.new(0, SHIP_Y + 9.5, 0)
	spawn.Parent = lobbyFolder

	-- Race-selection podiums & big lore book on the deck
	self.furnitureGenerator = LobbyFurnitureGenerator.new(self)
	self.furnitureGenerator:placeFurniture(lobbyFolder, SHIP_Y + 8.5)

	self.bookGenerator = LobbyBookGenerator.new(self)
	self.bookGenerator:createBigBook(lobbyFolder, Vector3.new(0, SHIP_Y + 9.5, -30))

	-- Dungeon portal (teleporter ring on deck)
	self:buildPortal(lobbyFolder)

	-- Interior lighting
	self:buildInteriorLights(lobbyFolder)

	return lobbyFolder
end

-- ── Interior deck ──────────────────────────────────────────────────────────

function LobbyGenerator:buildInteriorDeck(parent)
	-- Walkable floor sitting just above the disk's top surface
	local deck = Instance.new("Part")
	deck.Name     = "InteriorDeck"
	deck.Shape    = Enum.PartType.Cylinder
	deck.Size     = Vector3.new(1.0, 120, 120)
	deck.Color    = Color3.fromRGB(45, 50, 65)
	deck.Material = Enum.Material.SmoothPlastic
	deck.Anchored = true
	deck.TopSurface    = Enum.SurfaceType.Smooth
	deck.BottomSurface = Enum.SurfaceType.Smooth
	deck.CFrame   = CFrame.new(0, SHIP_Y + 8.5, 0) * CFrame.Angles(0, 0, math.rad(90))
	deck.Parent   = parent

	-- Deck edge accent ring (Neon)
	local ring = Instance.new("Part")
	ring.Name     = "DeckRing"
	ring.Shape    = Enum.PartType.Cylinder
	ring.Size     = Vector3.new(0.4, 122, 122)
	ring.Color    = Color3.fromRGB(0, 200, 255)
	ring.Material = Enum.Material.Neon
	ring.Anchored = true
	ring.CanCollide = false
	ring.CFrame   = CFrame.new(0, SHIP_Y + 8.6, 0) * CFrame.Angles(0, 0, math.rad(90))
	ring.Parent   = parent
end

-- ── Landing pad on the ground ──────────────────────────────────────────────

function LobbyGenerator:buildLandingPad(parent)
	local pad = Instance.new("Part")
	pad.Name     = "LandingPad"
	pad.Shape    = Enum.PartType.Cylinder
	pad.Size     = Vector3.new(1, 200, 200)
	pad.Color    = Color3.fromRGB(30, 30, 40)
	pad.Material = Enum.Material.Metal
	pad.Anchored = true
	pad.CFrame   = CFrame.new(0, -0.5, 0) * CFrame.Angles(0, 0, math.rad(90))
	pad.Parent   = parent

	-- Painted markings (cross lines)
	for _, rot in ipairs({0, 90}) do
		local stripe = Instance.new("Part")
		stripe.Name     = "Stripe"
		stripe.Size     = Vector3.new(0.4, 150, 6)
		stripe.Color    = Color3.fromRGB(255, 200, 0)
		stripe.Material = Enum.Material.Neon
		stripe.Anchored = true
		stripe.CanCollide = false
		stripe.CFrame   = CFrame.new(0, 0.2, 0) * CFrame.Angles(0, math.rad(rot), 0)
		stripe.Parent   = parent
	end

	-- Ground plane extending out from pad
	local ground = Instance.new("Part")
	ground.Name     = "Ground"
	ground.Size     = Vector3.new(1, 2000, 2000)
	ground.Color    = Color3.fromRGB(20, 20, 30)
	ground.Material = Enum.Material.SmoothPlastic
	ground.Anchored = true
	ground.CFrame   = CFrame.new(0, -1, 0) * CFrame.Angles(0, 0, math.rad(90))
	ground.Parent   = parent
end

-- ── Dungeon portal ─────────────────────────────────────────────────────────

function LobbyGenerator:buildPortal(parent)
	-- Glowing ring on the deck that sends players to dungeon
	local portalBase = Instance.new("Part")
	portalBase.Name     = "PortalBase"
	portalBase.Shape    = Enum.PartType.Cylinder
	portalBase.Size     = Vector3.new(1.0, 12, 12)
	portalBase.Color    = Color3.fromRGB(10, 10, 20)
	portalBase.Material = Enum.Material.SmoothPlastic
	portalBase.Anchored = true
	portalBase.CFrame   = CFrame.new(0, SHIP_Y + 9.0, 40) * CFrame.Angles(0, 0, math.rad(90))
	portalBase.Parent   = parent

	local portalRing = Instance.new("Part")
	portalRing.Name     = "PortalRing"
	portalRing.Shape    = Enum.PartType.Cylinder
	portalRing.Size     = Vector3.new(0.8, 14, 14)
	portalRing.Color    = Color3.fromRGB(100, 0, 255)
	portalRing.Material = Enum.Material.Neon
	portalRing.Anchored = true
	portalRing.CanCollide = false
	portalRing.CFrame   = CFrame.new(0, SHIP_Y + 9.2, 40) * CFrame.Angles(0, 0, math.rad(90))
	portalRing.Parent   = parent

	local light = Instance.new("PointLight")
	light.Color = Color3.fromRGB(100, 0, 255)
	light.Brightness = 3; light.Range = 30
	light.Parent = portalRing

	-- Touch detector
	local detector = Instance.new("Part")
	detector.Name     = "PortalDetector"
	detector.Shape    = Enum.PartType.Cylinder
	detector.Size     = Vector3.new(2, 12, 12)
	detector.Anchored = true
	detector.CanCollide = false
	detector.Transparency = 1
	detector.CFrame   = CFrame.new(0, SHIP_Y + 6, 30) * CFrame.Angles(0, 0, math.rad(90))
	detector.Parent   = parent

	-- Server will connect Touched to fire DungeonPortalEntered
	detector.Touched:Connect(function(hit)
		local player = game:GetService("Players"):GetPlayerFromCharacter(hit.Parent)
		if player then
			local ev = game:GetService("ReplicatedStorage"):FindFirstChild("DungeonPortalEntered")
			if ev then ev:FireClient(player, "Normal") end
		end
	end)

	-- Label
	local bg = Instance.new("BillboardGui")
	bg.Size = UDim2.new(0, 120, 0, 30)
	bg.StudsOffset = Vector3.new(0, 9, 0)
	bg.AlwaysOnTop = false
	bg.Parent = portalBase
	local lbl = Instance.new("TextLabel", bg)
	lbl.Size = UDim2.new(1, 0, 1, 0)
	lbl.BackgroundTransparency = 1
	lbl.TextColor3 = Color3.fromRGB(200, 150, 255)
	lbl.Font = Enum.Font.GothamBold
	lbl.TextScaled = true
	lbl.Text = "⚡ ENTER DUNGEON"
end

-- ── Interior lights ────────────────────────────────────────────────────────

function LobbyGenerator:buildInteriorLights(parent)
	local positions = {
		Vector3.new(-30, SHIP_Y + 10, -30),
		Vector3.new( 30, SHIP_Y + 10, -30),
		Vector3.new(-30, SHIP_Y + 10,  30),
		Vector3.new( 30, SHIP_Y + 10,  30),
		Vector3.new(  0, SHIP_Y + 10,   0),
	}
	local colors = {
		Color3.fromRGB(200, 200, 255),
		Color3.fromRGB(180, 220, 255),
		Color3.fromRGB(220, 200, 255),
	}
	for i, pos in ipairs(positions) do
		local p = Instance.new("Part")
		p.Shape = Enum.PartType.Ball; p.Size = Vector3.new(1,1,1)
		p.Anchored = true; p.CanCollide = false; p.Transparency = 1
		p.CFrame = CFrame.new(pos); p.Parent = parent
		local l = Instance.new("PointLight", p)
		l.Color = colors[((i-1) % #colors) + 1]
		l.Brightness = 2; l.Range = 45
	end
end

return LobbyGenerator
