-- lobby_generator.lua (REWRITE)
-- Builds the spaceship exterior lobby + landing pad + dungeon portal.
-- Spaceship is generated by spaceship_builder.lua.
-- Dungeon is at Z=2000; lobby is at Z=0.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Shared = ReplicatedStorage:WaitForChild("Shared")
local GameData = require(Shared:WaitForChild("game_data"))
local TweenService = game:GetService("TweenService")

local SpaceshipBuilder   = require(script.Parent:WaitForChild("spaceship_builder"))
local LobbyFurnitureGenerator = require(script.Parent:WaitForChild("lobby_furniture_generator"))
local LobbyBookGenerator = require(script.Parent:WaitForChild("lobby_book_generator"))

local LobbyGenerator = {}
LobbyGenerator.__index = LobbyGenerator

-- Lobby is centred at origin, floating high for the drop-in mechanic
-- Height is now defined in GameData.WORLD_CONFIG.lobbyHeight

function LobbyGenerator.new(parent)
	local self = setmetatable({}, LobbyGenerator)
	self.parent = parent or workspace
	self.holes = {}
	
	-- Note: Unlocking is triggered by GameManager on the server
	-- and visually handled by main.client.lua
	
	return self
end

function LobbyGenerator:generateLobby()
	local existing = self.parent:FindFirstChild("Lobby")
	if existing then existing:Destroy() end

	local lobbyFolder = Instance.new("Folder")
	lobbyFolder.Name  = "Lobby"
	lobbyFolder.Parent = self.parent

	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	-- Build the saucer (floats high for the drop holes)
	SpaceshipBuilder.build(lobbyFolder, Vector3.new(0, shipY, 0))

	-- Interior deck with holes
	self:buildInteriorDeck(lobbyFolder)

	-- Select Race Station
	self:buildRaceSelectionStation(lobbyFolder)

	-- Difficulty Drop Holes
	self:buildPortal(lobbyFolder)

	-- Interior lighting
	self:buildInteriorLights(lobbyFolder)

	return lobbyFolder
end

-- ── Interior deck ──────────────────────────────────────────────────────────

function LobbyGenerator:buildInteriorDeck(parent)
	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	-- We build 5 deck segments that sit BETWEEN the 5 drop holes
	local numHoles = 5
	local radius = 55
	
	for i = 1, numHoles do
		local holeAngle = (i-1) * (360 / numHoles)
		local segmentAngle = math.rad(holeAngle + (180 / numHoles))
		
		local p = Instance.new("Part")
		p.Name = "DeckPanel_" .. i
		p.Size = Vector3.new(35, 1, 45) -- Narrower to ensure gaps
		p.Position = Vector3.new(math.cos(segmentAngle) * 50, shipY + 8.5, math.sin(segmentAngle) * 50)
		p.CFrame = CFrame.lookAt(p.Position, Vector3.new(0, shipY + 8.5, 0)) * CFrame.Angles(0, math.rad(90), 0)
		p.Color = Color3.fromRGB(30, 32, 40)
		p.Material = Enum.Material.Metal
		p.Anchored = true
		p.Parent = parent
	end

	-- Central safe area (Spawn)
	local spawn = Instance.new("SpawnLocation")
	spawn.Name = "LobbySpawn"
	spawn.Size = Vector3.new(30, 1.2, 30)
	spawn.Color = Color3.fromRGB(50, 55, 75)
	spawn.Material = Enum.Material.Metal
	spawn.Anchored = true
	spawn.CFrame = CFrame.new(0, shipY + 9.0, 0)
	spawn.Parent = parent
	Instance.new("UICorner", spawn)

	-- Add a label to spawn
	local bg = Instance.new("BillboardGui")
	bg.Size = UDim2.new(0, 200, 0, 50)
	bg.StudsOffset = Vector3.new(0, 15, 0)
	bg.AlwaysOnTop = true
	bg.Parent = spawn
	local lbl = Instance.new("TextLabel", bg)
	lbl.Size = UDim2.new(1, 0, 1, 0)
	lbl.BackgroundTransparency = 1
	lbl.TextColor3 = Color3.fromRGB(100, 255, 255)
	lbl.Font = Enum.Font.GothamBold
	lbl.TextSize = 24
	lbl.Text = "COMMAND DECK"
end

-- ── Landing pad on the ground ──────────────────────────────────────────────

function LobbyGenerator:buildPortal(parent)
	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	-- Create five drop holes for different difficulties
	local diffs = {"Beginner", "Easy", "Normal", "Hard", "Insane"}
	local radius = 50
	for i, diff in ipairs(diffs) do
		local angle = math.rad((i-1) * (360 / #diffs))
		local pos = Vector3.new(math.cos(angle) * radius, shipY + 8.5, math.sin(angle) * radius)
		local color = GameData.DIFFICULTIES[diff].color
		self:buildDropHole(parent, pos, diff, color)
	end
end

function LobbyGenerator:buildDropHole(parent, pos, difficulty, color)
	-- The hole itself
	local hole = Instance.new("Part")
	hole.Name = "DropHole_" .. difficulty
	hole.Shape = Enum.PartType.Cylinder
	hole.Size = Vector3.new(2, 18, 18)
	hole.CFrame = CFrame.new(pos) * CFrame.Angles(0, 0, math.rad(90))
	hole.Transparency = 1
	hole.Anchored = true
	hole.CanCollide = false
	hole.Parent = parent

	-- Shield (LOCKED STATE)
	local shield = Instance.new("Part")
	shield.Name = "HoleShield"
	shield.Shape = Enum.PartType.Cylinder
	shield.Size = Vector3.new(1.5, 18, 18)
	shield.Color = Color3.fromRGB(255, 50, 50) -- Locked red
	shield.Material = Enum.Material.ForceField
	shield.Transparency = 0.5
	shield.Anchored = true
	shield.CanCollide = true -- BLOCKS FALLING
	shield.CFrame = hole.CFrame
	shield.Parent = parent

	-- Glowing rim
	local rim = Instance.new("Part")
	rim.Name = "HoleRim"
	rim.Shape = Enum.PartType.Cylinder
	rim.Size = Vector3.new(0.5, 20, 20)
	rim.Color = color
	rim.Material = Enum.Material.Neon
	rim.Anchored = true
	rim.CanCollide = false
	rim.CFrame = hole.CFrame
	rim.Parent = parent
	
	table.insert(self.holes, {hole = hole, shield = shield, rim = rim, difficulty = difficulty})
	
	local light = Instance.new("PointLight")
	light.Color = color
	light.Brightness = 5; light.Range = 20
	light.Parent = rim

	-- Difficulty Label
	local bg = Instance.new("BillboardGui")
	bg.Size = UDim2.new(0, 200, 0, 50)
	bg.StudsOffset = Vector3.new(0, 10, 0)
	bg.AlwaysOnTop = true
	bg.Parent = rim
	local lbl = Instance.new("TextLabel", bg)
	lbl.Size = UDim2.new(1, 0, 1, 0)
	lbl.BackgroundTransparency = 1
	lbl.TextColor3 = color
	lbl.Font = Enum.Font.GothamBold
	lbl.TextSize = 22
	lbl.Text = "DROP: " .. difficulty:upper()
	lbl.Parent = bg

	-- Particle effect (falling energy)
	local att = Instance.new("Attachment", rim)
	local particles = Instance.new("ParticleEmitter")
	particles.Texture = "rbxassetid://244221446"
	particles.Color = ColorSequence.new(color)
	particles.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0), NumberSequenceKeypoint.new(1, 1)})
	particles.Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 2), NumberSequenceKeypoint.new(1, 0)})
	particles.Speed = NumberRange.new(20, 40)
	particles.EmissionDirection = Enum.NormalId.Bottom
	particles.Lifetime = NumberRange.new(2, 4)
	particles.Rate = 50
	particles.Parent = att

	hole.Touched:Connect(function(hit)
		if shield.Parent == nil then -- Only trigger if unlocked
			local player = game:GetService("Players"):GetPlayerFromCharacter(hit.Parent)
			if player then
				local ev = game:GetService("ReplicatedStorage"):FindFirstChild("DungeonPortalEntered")
				if ev then ev:FireClient(player, difficulty) end
			end
		end
	end)
end

function LobbyGenerator:unlockHoles()
	-- Server-side unlocking: Clear collisions and destroy shields
	for _, data in ipairs(self.holes) do
		if data.shield and data.shield.Parent then
			data.shield.CanCollide = false
			data.shield:Destroy()
			
			-- Update label to READY
			local bg = data.rim:FindFirstChildWhichIsA("BillboardGui")
			if bg then
				local lbl = bg:FindFirstChildWhichIsA("TextLabel")
				if lbl then
					lbl.Text = "READY: " .. data.difficulty:upper()
					lbl.TextColor3 = Color3.fromRGB(50, 255, 100)
				end
			end
		end
	end
end

function LobbyGenerator:buildRaceSelectionStation(parent)
	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	local station = Instance.new("Model")
	station.Name = "RaceSelectionStation"
	station.Parent = parent

	-- Platform
	local platform = Instance.new("Part")
	platform.Size = Vector3.new(40, 2, 40)
	platform.Position = Vector3.new(0, shipY + 8.5, -50)
	platform.Color = Color3.fromRGB(30, 30, 40)
	platform.Material = Enum.Material.DiamondPlate
	platform.Anchored = true
	platform.Parent = station

	-- Holographic Label
	local bg = Instance.new("BillboardGui")
	bg.Size = UDim2.new(0, 300, 0, 80)
	bg.StudsOffset = Vector3.new(0, 15, 0)
	bg.AlwaysOnTop = true
	bg.Parent = platform
	local lbl = Instance.new("TextLabel", bg)
	lbl.Size = UDim2.new(1, 0, 1, 0)
	lbl.BackgroundTransparency = 1
	lbl.TextColor3 = Color3.fromRGB(255, 200, 50)
	lbl.Font = Enum.Font.GothamBold
	lbl.TextSize = 32
	lbl.Text = "SELECT RACE"
	lbl.Parent = bg

	-- Complicated Furniture (Podiums)
	local races = {"Human", "Elf", "Dwarf", "Orc"}
	for i, race in ipairs(races) do
		local angle = math.rad((i-1) * (360 / #races))
		local r = 12
		local pPos = platform.Position + Vector3.new(math.cos(angle) * r, 3, math.sin(angle) * r)
		
		local podium = Instance.new("Part")
		podium.Size = Vector3.new(4, 6, 4)
		podium.Position = pPos
		podium.Color = Color3.fromRGB(50, 50, 60)
		podium.Material = Enum.Material.Metal
		podium.Anchored = true
		podium.Parent = station

		local screen = Instance.new("Part")
		screen.Size = Vector3.new(3, 2, 0.2)
		screen.Position = pPos + Vector3.new(0, 4, 0)
		screen.Color = Color3.fromRGB(0, 150, 255)
		screen.Material = Enum.Material.Neon
		screen.Transparency = 0.5
		screen.Anchored = true
		screen.Parent = station

		local pbg = Instance.new("BillboardGui")
		pbg.Size = UDim2.new(0, 100, 0, 30)
		pbg.StudsOffset = Vector3.new(0, 2, 0)
		pbg.Parent = screen
		local plbl = Instance.new("TextLabel", pbg)
		plbl.Size = UDim2.new(1, 0, 1, 0)
		plbl.BackgroundTransparency = 1
		plbl.TextColor3 = Color3.new(1,1,1)
		plbl.Text = race
		plbl.Font = Enum.Font.GothamBold
		plbl.TextSize = 18
	end
end

-- ── Interior lights ────────────────────────────────────────────────────────

function LobbyGenerator:buildInteriorLights(parent)
	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	local positions = {
		Vector3.new(-30, shipY + 10, -30),
		Vector3.new( 30, shipY + 10, -30),
		Vector3.new(-30, shipY + 10,  30),
		Vector3.new( 30, shipY + 10,  30),
		Vector3.new(  0, shipY + 10,   0),
	}
	local colors = {
		Color3.fromRGB(200, 200, 255),
		Color3.fromRGB(180, 220, 255),
		Color3.fromRGB(220, 200, 255),
	}
	for i, pos in ipairs(positions) do
		local p = Instance.new("Part")
		p.Shape = Enum.PartType.Ball; p.Size = Vector3.new(1,1,1)
		p.Anchored = true; p.CanCollide = false; p.Transparency = 1
		p.CFrame = CFrame.new(pos); p.Parent = parent
		local l = Instance.new("PointLight", p)
		l.Color = colors[((i-1) % #colors) + 1]
		l.Brightness = 2; l.Range = 45
	end
end

return LobbyGenerator
