-- lobby_generator.lua (REWRITE)
-- Builds the spaceship exterior lobby + landing pad + dungeon portal.
-- Spaceship is generated by spaceship_builder.lua.
-- Dungeon is at Z=2000; lobby is at Z=0.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Shared = ReplicatedStorage:WaitForChild("Shared")
local GameData = require(Shared:WaitForChild("game_data"))
local TweenService = game:GetService("TweenService")

local SpaceshipBuilder   = require(script.Parent:WaitForChild("spaceship_builder"))
local LobbyFurnitureGenerator = require(script.Parent:WaitForChild("lobby_furniture_generator"))
local LobbyBookGenerator = require(script.Parent:WaitForChild("lobby_book_generator"))

local LobbyGenerator = {}
LobbyGenerator.__index = LobbyGenerator

-- Lobby is centred at origin, floating high for the drop-in mechanic
-- Height is now defined in GameData.WORLD_CONFIG.lobbyHeight

function LobbyGenerator.new(parent)
	local self = setmetatable({}, LobbyGenerator)
	self.parent = parent or workspace
	self.holes = {}
	
	-- Note: Unlocking is triggered by GameManager on the server
	-- and visually handled by main.client.lua
	
	return self
end

function LobbyGenerator:generateLobby()
	local existing = self.parent:FindFirstChild("Lobby")
	if existing then existing:Destroy() end

	local lobbyFolder = Instance.new("Folder")
	lobbyFolder.Name  = "Lobby"
	lobbyFolder.Parent = self.parent

	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	-- Build the saucer (floats high for the drop holes)
	SpaceshipBuilder.build(lobbyFolder, Vector3.new(0, shipY, 0))

	-- Interior deck (SOLID)
	self:buildSolidDeck(lobbyFolder)

	-- Select Race Station
	self:buildRaceSelectionStation(lobbyFolder)

	-- Launch Pads (Replacing drop holes at SOUTH)
	self:buildSouthDropHoles(lobbyFolder)

	-- Interior lighting
	self:buildInteriorLights(lobbyFolder)

	return lobbyFolder
end

-- ── Interior deck ──────────────────────────────────────────────────────────

function LobbyGenerator:buildSolidDeck(parent)
	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	
	-- Main Deck (Central and North)
	local deck = Instance.new("Part")
	deck.Name = "MainDeck"
	deck.Size = Vector3.new(140, 1, 100)
	deck.Position = Vector3.new(0, shipY + 8.5, -20)
	deck.Color = Color3.fromRGB(20, 22, 28)
	deck.Material = Enum.Material.Metal
	deck.Anchored = true
	deck.Parent = parent
	Instance.new("UICorner", deck)

	-- South Walkway (around the holes)
	local walkway = Instance.new("Part")
	walkway.Name = "SouthWalkway"
	walkway.Size = Vector3.new(140, 1, 20)
	walkway.Position = Vector3.new(0, shipY + 8.5, 60)
	walkway.Color = Color3.fromRGB(25, 27, 35)
	walkway.Material = Enum.Material.Metal
	walkway.Anchored = true
	walkway.Parent = parent

	-- Central safe area (Spawn)
	local spawn = Instance.new("SpawnLocation")
	spawn.Name = "LobbySpawn"
	spawn.Size = Vector3.new(30, 1.2, 30)
	spawn.Color = Color3.fromRGB(40, 45, 65)
	spawn.Material = Enum.Material.Metal
	spawn.Anchored = true
	spawn.CFrame = CFrame.new(0, shipY + 9.0, 0)
	spawn.Parent = parent
	Instance.new("UICorner", spawn)
end

-- ── Landing pad on the ground ──────────────────────────────────────────────

function LobbyGenerator:buildSouthDropHoles(parent)
	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	local diffs = {"Beginner", "Easy", "Normal", "Hard", "Insane"}
	local startX = -40
	local spacing = 20
	local zPos = 40 -- South area gap

	for i, diff in ipairs(diffs) do
		local pos = Vector3.new(startX + (i-1) * spacing, shipY + 8.5, zPos)
		local color = GameData.DIFFICULTIES[diff].color
		self:buildDropHole(parent, pos, diff, color)
	end
end

function LobbyGenerator:buildDropHole(parent, pos, difficulty, color)
	-- The physical hole rim
	local rim = Instance.new("Part")
	rim.Name = "HoleRim_" .. difficulty
	rim.Shape = Enum.PartType.Cylinder
	rim.Size = Vector3.new(0.5, 14, 14)
	rim.CFrame = CFrame.new(pos) * CFrame.Angles(0, 0, math.rad(90))
	rim.Color = color
	rim.Material = Enum.Material.Neon
	rim.Anchored = true
	rim.CanCollide = true -- Walkable rim
	rim.Parent = parent

	-- Particle effect (falling energy)
	local att = Instance.new("Attachment", rim)
	local particles = Instance.new("ParticleEmitter")
	particles.Texture = "rbxassetid://244221446"
	particles.Color = ColorSequence.new(color)
	particles.Size = NumberSequence.new(2, 0)
	particles.Speed = NumberRange.new(10, 30)
	particles.EmissionDirection = Enum.NormalId.Bottom
	particles.Rate = 50
	particles.Parent = att

	-- Invisible Trigger (Fires cinematic)
	local trigger = Instance.new("Part")
	trigger.Name = "Trigger_" .. difficulty
	trigger.Shape = Enum.PartType.Cylinder
	trigger.Size = Vector3.new(2, 12, 12)
	trigger.CFrame = rim.CFrame
	trigger.Transparency = 1
	trigger.Anchored = true
	trigger.CanCollide = false -- FALL THROUGH
	trigger.Parent = parent

	trigger.Touched:Connect(function(hit)
		local char = hit.Parent
		local player = game:GetService("Players"):GetPlayerFromCharacter(char)
		if player then
			local ev = ReplicatedStorage:FindFirstChild("InternalRequestLaunch")
			if ev then ev:Fire(player, difficulty) end
		end
	end)

	-- Label
	local bg = Instance.new("BillboardGui")
	bg.Size = UDim2.new(0, 150, 0, 40)
	bg.StudsOffset = Vector3.new(0, 6, 0)
	bg.AlwaysOnTop = true
	bg.Parent = rim
	local lbl = Instance.new("TextLabel", bg)
	lbl.Size = UDim2.new(1, 0, 1, 0)
	lbl.BackgroundTransparency = 1
	lbl.TextColor3 = color
	lbl.Font = Enum.Font.GothamBold
	lbl.TextSize = 18
	lbl.Text = "DROP: " .. difficulty:upper()
end

function LobbyGenerator:buildRaceSelectionStation(parent)
	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	local station = Instance.new("Model")
	station.Name = "RaceSelectionStation"
	station.Parent = parent

	-- Platform
	local platform = Instance.new("Part")
	platform.Size = Vector3.new(40, 2, 40)
	platform.Position = Vector3.new(0, shipY + 8.5, -50)
	platform.Color = Color3.fromRGB(30, 30, 40)
	platform.Material = Enum.Material.DiamondPlate
	platform.Anchored = true
	platform.Parent = station

	-- Holographic Label
	local bg = Instance.new("BillboardGui")
	bg.Size = UDim2.new(0, 300, 0, 80)
	bg.StudsOffset = Vector3.new(0, 15, 0)
	bg.AlwaysOnTop = true
	bg.Parent = platform
	local lbl = Instance.new("TextLabel", bg)
	lbl.Size = UDim2.new(1, 0, 1, 0)
	lbl.BackgroundTransparency = 1
	lbl.TextColor3 = Color3.fromRGB(255, 200, 50)
	lbl.Font = Enum.Font.GothamBold
	lbl.TextSize = 32
	lbl.Text = "SELECT RACE"
	lbl.Parent = bg

	-- Complicated Furniture (Podiums)
	local races = {"Human", "Elf", "Dwarf", "Orc"}
	for i, race in ipairs(races) do
		local angle = math.rad((i-1) * (360 / #races))
		local r = 12
		local pPos = platform.Position + Vector3.new(math.cos(angle) * r, 3, math.sin(angle) * r)
		
		local podium = Instance.new("Part")
		podium.Size = Vector3.new(4, 6, 4)
		podium.Position = pPos
		podium.Color = Color3.fromRGB(50, 50, 60)
		podium.Material = Enum.Material.Metal
		podium.Anchored = true
		podium.Parent = station

		local prompt = Instance.new("ProximityPrompt")
		prompt.ActionText = "Open Selection"
		prompt.ObjectText = race:upper() .. " DATA"
		prompt.HoldDuration = 0.5
		prompt.Parent = podium
		prompt.Triggered:Connect(function(player)
			local ev = ReplicatedStorage:FindFirstChild("RaceSelectionRequested")
			if ev then ev:FireClient(player) end
		end)

		local screen = Instance.new("Part")
		screen.Size = Vector3.new(3, 2, 0.2)
		screen.Position = pPos + Vector3.new(0, 4, 0)
		screen.Color = Color3.fromRGB(0, 150, 255)
		screen.Material = Enum.Material.Neon
		screen.Transparency = 0.5
		screen.Anchored = true
		screen.Parent = station

		local pbg = Instance.new("BillboardGui")
		pbg.Size = UDim2.new(0, 100, 0, 30)
		pbg.StudsOffset = Vector3.new(0, 2, 0)
		pbg.Parent = screen
		local plbl = Instance.new("TextLabel", pbg)
		plbl.Size = UDim2.new(1, 0, 1, 0)
		plbl.BackgroundTransparency = 1
		plbl.TextColor3 = Color3.new(1,1,1)
		plbl.Text = race
		plbl.Font = Enum.Font.GothamBold
		plbl.TextSize = 18
	end
end

-- ── Interior lights ────────────────────────────────────────────────────────

function LobbyGenerator:buildInteriorLights(parent)
	local shipY = GameData.WORLD_CONFIG.lobbyHeight
	local positions = {
		Vector3.new(-30, shipY + 10, -30),
		Vector3.new( 30, shipY + 10, -30),
		Vector3.new(-30, shipY + 10,  30),
		Vector3.new( 30, shipY + 10,  30),
		Vector3.new(  0, shipY + 10,   0),
	}
	local colors = {
		Color3.fromRGB(200, 200, 255),
		Color3.fromRGB(180, 220, 255),
		Color3.fromRGB(220, 200, 255),
	}
	for i, pos in ipairs(positions) do
		local p = Instance.new("Part")
		p.Shape = Enum.PartType.Ball; p.Size = Vector3.new(1,1,1)
		p.Anchored = true; p.CanCollide = false; p.Transparency = 1
		p.CFrame = CFrame.new(pos); p.Parent = parent
		local l = Instance.new("PointLight", p)
		l.Color = colors[((i-1) % #colors) + 1]
		l.Brightness = 2; l.Range = 45
	end
end

return LobbyGenerator
