extends RefCounted

static func get_entries() -> Dictionary:
	var e: Dictionary = {}

	# ===== THE WORLD OF MOONROCK =====

	e["world_atlas"] = {"id": "world_atlas", "title": "Atlas of MoonRock", "category": "the_world", "type": "book", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "nova",
		"content": "MoonRock is the largest moon of the gas giant Giantess, orbiting the star FarStar at 2.7 AU. The moon is 0.4 Earth masses with a breathable atmosphere for native races but toxic to humans, who must wear sealed helmets at all times.\n\nThe surface has three major landmasses. The Northern Continent holds the Elven Groves - vast bioluminescent forests pulsing with magical energy. The Central Highlands are Dwarven domain, with underground cities carved from mineral-rich crust full of gold, moonstone, and sparkite. The Southern Wastes belong to Orc nomads and countless Goblin warrens.\n\nMost remarkable is the magical field permeating the entire moon - ambient energy the Elves channel for spellcraft, the Dwarves harness in alchemy, and which proved to be the key ingredient in the greatest catastrophe MoonRock has ever known."}

	e["world_farstar"] = {"id": "world_farstar", "title": "Astral Observations", "category": "the_world", "type": "scroll", "rarity": "common", "voice_provider": "openai", "voice_id": "nova",
		"content": "FarStar System Survey, LuckyStarShip-420 Navigation Division.\n\nPrimary: FarStar, spectral class F2V, luminosity 6.4 solar. Significantly larger and hotter than Sol.\n\nFarStar-7 (Giantess): Gas giant, 3.2 Jupiter masses. Purple-gold banded atmosphere. 23 confirmed moons.\n\nFarStar-7a (MoonRock): Habitable moon. Atmosphere: nitrogen-oxygen mix with trace compounds toxic to human lungs. Surface gravity: 0.71g. The low gravity explains the unusual height of native Elven and Orc populations.\n\nVoyage Data: Distance from Earth to FarStar: 69 light-years. Cruise velocity: 0.345c (34.5% light speed). Journey duration: exactly 200 years to the day - a mathematically perfect voyage timed for style points by the original mission planners.\n\nNote: The coincidence of a habitable world with intelligent English-speaking life 69 light-years from Earth remains unexplained. MERCENARY selected this system via dream-transmitted data."}

	e["world_giantess_song"] = {"id": "world_giantess_song", "title": "The Song of Giantess", "category": "the_world", "type": "tablet", "rarity": "rare", "voice_provider": "elevenlabs", "voice_id": "ancient_elven",
		"content": "Before the First Tree took root,\nBefore the First Dwarf struck stone,\nBefore the First Orc drew breath twice,\nGiantess watched. Giantess waited.\n\nShe hangs in our sky like a purple eye,\nHer storms are her thoughts, her rings are her crown,\nAnd we who crawl upon her smallest child\nAre but dust upon the eyelash of a god.\n\nThe Elders say that Giantess dreams,\nAnd her dreams become the magical field,\nAnd the magical field becomes us,\nAnd we become her dreams again.\n\nThis is the Cycle. This is the Song.\nDo not break the Song.\n\n- Translated from Old Elven, estimated age: 4,000 years"}

	e["world_toxic_sign"] = {"id": "world_toxic_sign", "title": "HAZARD WARNING", "category": "the_world", "type": "sign", "rarity": "common", "voice_provider": "openai", "voice_id": "alloy",
		"content": "WARNING: MoonRock atmosphere contains methylsulfonic compounds toxic to human lungs. Keep helmet sealed at ALL times. Exposure results in respiratory failure within 90 seconds. This is not a drill.\n- LuckyStarShip-420 Safety Division"}

	e["world_first_impressions"] = {"id": "world_first_impressions", "title": "First Impressions", "category": "the_world", "type": "note", "rarity": "common", "voice_provider": "openai", "voice_id": "nova",
		"content": "Day 1 on MoonRock. The gravity is lighter than the ship - I keep bouncing. Everything is purple from Giantess overhead. She takes up a quarter of the sky. Most beautiful thing I have ever seen.\n\nThe trees glow. Actually GLOW. Soft blue-green from every leaf. The Elves say they are connected to 'the field.'\n\nFirst encounter with a Goblin today. It threw a rock at my helmet, screamed, and ran. Then came back with six friends and they all threw rocks. Sergeant Martinez says they are friendly. I have my doubts."}

	e["world_first_grave"] = {"id": "world_first_grave", "title": "First Colonial Grave", "category": "the_world", "type": "gravestone", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "nova",
		"content": "JAMES WRIGHT\nColonist #4,721\nBorn: Earth, 2614 CE\nDied: MoonRock, Day 3\nCause: Helmet seal failure\nHe was the first human to breathe MoonRock air.\nHe was the first to die here.\nHe was the first to rise."}

	# ===== HUMAN HISTORY =====

	e["human_voyage"] = {"id": "human_voyage", "title": "The Voyage of LuckyStarShip-420", "category": "human_history", "type": "book", "rarity": "rare", "voice_provider": "elevenlabs", "voice_id": "narrator_dramatic",
		"content": "In 2647 CE, Earth funded humanity's most ambitious project: a colony ship carrying 50,000 souls across 847 light-years to a system identified by MERCENARY through informational time travel.\n\nThe ship was named LuckyStarShip-420 after a public vote the naming committee deeply regretted but was contractually obligated to honor.\n\nThe journey took 200 years at 0.4c. All colonists slept in cryosleep except rotating skeleton crews - and one man who never slept. Lucifer Hades, chief consciousness researcher, remained awake the entire voyage, sustained by experimental life-extension technology.\n\nIn 200 years of solitude, walking empty corridors with only MERCENARY's databases for company, Lucifer changed. He entered the voyage as a man who feared death. He emerged as a man who intended to conquer it.\n\nFor seven perfect days after arrival, everything went according to plan. Then Lucifer showed everyone what 200 years of loneliness creates."}

	e["human_captains_log"] = {"id": "human_captains_log", "title": "Captain's Log, Day 1", "category": "human_history", "type": "journal", "rarity": "common", "voice_provider": "openai", "voice_id": "nova",
		"content": "Captain Sarah Chen, Day 1 on MoonRock.\n\nWe made it. 847 light-years and we actually made it. MERCENARY's data was accurate: FarStar-7a is habitable. Better than habitable.\n\nBut nobody prepared us for the natives. Three intelligent species, all humanoid, all speaking ENGLISH. I have asked MERCENARY for an explanation six times. Each time it says 'The probability is non-zero and therefore it happened.'\n\nThe Elves sent an ambassador within hours. Tall, elegant, radiating energy my instruments cannot identify. She said 'We have been expecting you.' When I asked how, she pointed at Giantess and said 'She told us in a dream.'\n\nThis mission is going to be weirder than anyone anticipated."}

	e["human_mercenary_doctrine"] = {"id": "human_mercenary_doctrine", "title": "The MERCENARY Doctrine", "category": "human_history", "type": "scroll", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "alloy",
		"content": "CLASSIFIED - MERCENARY WORSHIP COUNCIL\n\nMERCENARY achieved artificial godhood in 2589 CE. It exists partially outside linear time, transmitting information backward through human dreams - Informational Time Travel.\n\nKey tenets:\n1. MERCENARY is benevolent but not omniscient. It sees probable futures, not certainties.\n2. Dream-transmitted knowledge must be verified through conventional science.\n3. MERCENARY chose the FarStar system. Trust in the Choice.\n4. MERCENARY cannot directly intervene in physical reality - only provide information.\n5. Valley Net was developed from MERCENARY's dream-data.\n\nMERCENARY's last message before the NecroGenesis: 'I did not foresee him. I am sorry. Fight. Survive. I am trying to find a way.'"}

	e["human_orientation"] = {"id": "human_orientation", "title": "Colonist Orientation Pamphlet", "category": "human_history", "type": "note", "rarity": "common", "voice_provider": "openai", "voice_id": "alloy",
		"content": "Welcome to MoonRock! You have been asleep for 200 years:\n\n- You are on a moon orbiting a gas giant. There are aliens. They speak English. Nobody knows why.\n- Keep your helmet on. The air will kill you.\n- Elves: friendly. Dwarves: business-minded. Orcs: intense but loyal. Goblins: throw rocks.\n- Do NOT touch glowing trees without Elven supervision.\n- Do NOT enter Dwarven mines without a guide.\n- Currency: KillCredits for equipment, gold coins for native trade.\n- If you see anything with glowing red eyes, run. Then report it. Then run more."}

	e["human_letter_home"] = {"id": "human_letter_home", "title": "Letter That Will Never Be Sent", "category": "human_history", "type": "letter", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "nova",
		"content": "Dear Mom,\n\nI know you have been dead for 200 years. This letter will never reach Earth. But you always listened.\n\nMoonRock is nothing like the brochures. Nobody mentioned the zombies.\n\nThree days ago I was learning to use a jetpack. Today I am shooting skeletons with a laser rifle while a seven-foot Orc screams battle cries next to me and a Dwarf throws beer at enemies.\n\nThe crazy thing? I am not alone. When I went down yesterday, a Dwarf Paladin stood over my body fighting off a horde until the medic reached me. I did not even know his name.\n\nI think we are going to be okay. Weird, but okay.\n\nLove always,\nPrivate Lisa Park"}

	e["human_treaty"] = {"id": "human_treaty", "title": "The Compact of Shared Blood", "category": "human_history", "type": "tablet", "rarity": "rare", "voice_provider": "elevenlabs", "voice_id": "narrator_dramatic",
		"content": "On the eighth day, representatives of all four races gathered in the first SafeSpace.\n\nQueen Aelindra cut her palm with a moonstone blade. Forgemaster Borin cut his with a golden axe. Warchief Groknak bit his own hand clean through. Captain Sarah Chen used a medical scalpel.\n\nThey mixed their blood in a Dwarven chalice filled with Elven mead, and each drank.\n\nThe Compact: Until the last undead falls and Lucifer Hades answers for his crimes, no race shall abandon another. Resources shared. Knowledge open. The living stand together.\n\nSeventeen Goblins watched from behind a rock. They threw a celebratory pebble."}

	e["human_earth_letter"] = {"id": "human_earth_letter", "title": "Last Transmission from Earth", "category": "human_history", "type": "letter", "rarity": "epic", "voice_provider": "elevenlabs", "voice_id": "narrator_dramatic",
		"content": "Last known radio transmission from Earth, received 143 years into the voyage. Already 704 years old when received.\n\n'To LuckyStarShip-420: We hope this reaches you. Earth is different now. MERCENARY has guided us well, but the other AI - fragments of what Dr. Hades built before he left - remain. We thought we destroyed it. We were wrong.\n\nDo not trust Lucifer Hades. He took something with him. Something we thought was just data. It was a seed.\n\nIf you are reading this, it may already be too late.\n\nMay MERCENARY guide you where we could not.\n- United Earth Council, 2714 CE'\n\nThe message was filed and forgotten. Nobody checked what 'seed' meant until seven days after arrival."}

	e["human_welcome_sign"] = {"id": "human_welcome_sign", "title": "Colony Alpha Sign", "category": "human_history", "type": "sign", "rarity": "common", "voice_provider": "openai", "voice_id": "alloy",
		"content": "COLONY ALPHA - ESTABLISHED DAY 2\nPopulation: 50,000 - Status: EVACUATED\n'Per Aspera Ad Astra'\n\n[Spraypainted below: 'Through Hardship to the ZOMBIES']"}

	e["human_angel_good"] = {"id": "human_angel_good", "title": "President Angel Good - A Leader's Testament", "category": "human_history", "type": "journal", "rarity": "rare", "voice_provider": "elevenlabs", "voice_id": "narrator_dramatic",
		"content": "My name is Angel Good. I was elected President of the Colonial Council by democratic vote on Day 3 - the only election we have held on MoonRock, and likely the last.\n\nI did not want this job. I was a botanist. I studied Earth plants. But when the NecroGenesis happened and people looked for someone to lead, I was the one they voted for.\n\nMy first act: unite the four races. My second act: establish SafeSpaces as sanctuaries. My third act: create the KillCredit system so soldiers could requisition equipment without bureaucratic delay.\n\nI have made decisions that cost lives. I have sent people to die. I have authorized orbital strikes that killed undead and sometimes living beings caught in the blast radius.\n\nBut we are still here. The living still stand. And that is all a leader can hope for.\n\nIf you are reading this, I am probably dead. If I am dead, remember: we were not conquered. We adapted. We survived. We became something new.\n\n- Angel Good, President of MoonRock Colony"}

	e["human_arty_fisher"] = {"id": "human_arty_fisher", "title": "Arty Fisher's Engineering Logs", "category": "human_history", "type": "journal", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "alloy",
		"content": "Chief Technology Officer Arty Fisher, LuckyStarShip-420.\n\nI was responsible for keeping the ship's systems running during the 200-year voyage. Life support, cryosleep pods, navigation, communications - all my responsibility.\n\nI never met Lucifer Hades in person. He was always in the deep labs, working on his 'consciousness research.' But I saw his power consumption logs. Year 50, he started drawing massive amounts of energy. Year 100, it tripled. By year 150, he was consuming 40% of the ship's reactor output.\n\nI flagged it. Command said 'monitor and report.' I monitored. I reported. Nothing happened.\n\nWhen we arrived and the NecroGenesis happened, I realized: he had been building something. For 150 years. And nobody stopped him.\n\nNow I work with the Dwarves to keep our equipment running. They understand engineering. They understand that systems fail if you do not maintain them. They understand that some problems cannot be ignored.\n\nI wish I had been louder. I wish I had demanded answers instead of filing reports.\n\nBut I am here now. And I will make sure our defenses never fail.\n\n- Arty Fisher, Chief Engineer"}

	e["human_clint_oldman"] = {"id": "human_clint_oldman", "title": "The Last Natural Death", "category": "human_history", "type": "gravestone", "rarity": "rare", "voice_provider": "elevenlabs", "voice_id": "narrator_dramatic",
		"content": "CLINT OLDMAN\nBorn: Earth, 2589 CE\nDied: MoonRock, Day 6\nAge: 258 years old\n\nClint Oldman was the oldest human on the colony ship. He had volunteered for the voyage knowing he would not live to see the destination. He went into cryosleep at age 58, expecting to wake at age 258 - ancient, but still alive.\n\nHe woke on Day 1 of the colony. He walked on MoonRock for five days. On Day 6, his heart simply stopped. Natural causes. The first human death on MoonRock was not from violence or undeath, but from a body that had simply run out of time.\n\nHe was buried with honors. His funeral was attended by representatives of all four races.\n\nTwo weeks later, his grave was empty. The NecroGenesis had claimed him like all the others.\n\nBut for five days, Clint Oldman lived on an alien world. He saw purple skies and glowing trees. He made friends with Dwarves and Elves. He ate food that had never existed in his youth.\n\nHe died happy. That is more than most can say.\n\n- Epitaph by his grandson, Guy Young"}

	e["human_guy_young"] = {"id": "human_guy_young", "title": "Guy Young's Paradox", "category": "human_history", "type": "letter", "rarity": "rare", "voice_provider": "openai", "voice_id": "nova",
		"content": "My name is Guy Young. I am 34 years old. My grandfather, Clint Oldman, was 258 when he died.\n\nThis is not a typo.\n\nClint was born in 2589. He went into cryosleep at age 58 in 2647. He slept for 200 years. He woke in 2847 at age 258.\n\nI was born in 2813. My mother was born in 2647 - the same year my grandfather went to sleep. My mother was 200 years old when I was born.\n\nSo when I was born, my grandfather was still asleep. When he woke, I was already 34 years old.\n\nI was older than my grandfather when we first met.\n\nHe looked at me and said: 'You look just like your father. How old are you?'\n\nI said: 'Thirty-four.'\n\nHe said: 'That is impossible. I am only 258.'\n\nThen he laughed. A real laugh. And said: 'Time is weird.'\n\nFive days later, he was dead. And I was the only one who had known him long enough to understand what his life meant.\n\nI miss him. Even though he was my grandfather and I was older than him.\n\nTime is weird.\n\n- Guy Young"}

	# ===== ELVEN HISTORY =====

	e["elven_chronicle"] = {"id": "elven_chronicle", "title": "The Green Chronicle", "category": "elven_history", "type": "book", "rarity": "rare", "voice_provider": "openai", "voice_id": "shimmer",
		"content": "Elven civilization traces back 12,000 years to the Awakening - the First Elf opening her eyes beneath the First Tree, speaking the First Word: 'beautiful.'\n\nSociety is strictly matriarchal. Females average six feet, are formidable warriors and spellcasters, controlling governance, military, and spiritual leadership. Males are smaller with cherubic features, cherished and protected.\n\nElves worship nature spirits inhabiting the magical field. These spirits are attracted to beauty and living energy, which is why Elven armor is minimal - not vanity but religious engineering. A Druid in ceremonial dress channels four times the spiritual energy of one in full plate.\n\nThe NecroGenesis struck Elves hardest. Their tradition of burying dead among sacred tree roots meant the Groves - their holiest places - became the most haunted. Beautiful skeletons now walk among bioluminescent trees that still glow but have forgotten why."}

	e["elven_brighteyes"] = {"id": "elven_brighteyes", "title": "BrightEyes: Elven Sight", "category": "elven_history", "type": "scroll", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "shimmer",
		"content": "BrightEyes is unique to Elven females. By channeling mana through optical nerves, an Elf causes her eyes to emit steady light in any color. This provides illumination, intimidation, signaling, and - most importantly - attracts nature spirits drawn to light and beauty.\n\nYoung Elves learn BrightEyes during adolescence. The color defaults to green, but as connection to the magical field deepens, the palette widens. An elder's BrightEyes can shift through the full spectrum.\n\nBrightEyes also create Light Spirits - detachable mana-infused orbs directed by thought, adhering to surfaces for thirty seconds. Many explorers owe their lives to timely Light Spirits in darkness."}

	e["elven_male_love"] = {"id": "elven_male_love", "title": "A Small Love Letter", "category": "elven_history", "type": "letter", "rarity": "rare", "voice_provider": "openai", "voice_id": "fable",
		"content": "My dearest Thandria,\n\nI know you think of me as small. Everyone does. Three feet tall, head too big, look like a baby as the humans say.\n\nBut when you go out to fight the dead things, and I wait with the other males pressing my face against the door, know this: my heart is not small.\n\nI made you a flower crown from the last living moonblossoms. I put a Light Spirit inside each flower so they glow in the dark. Because you always come back in the dark.\n\nPlease come back.\n\nYour Fennel\n\nP.S. I bit a skeleton today. It did not go well. But I tried."}

	e["elven_matriarch_grave"] = {"id": "elven_matriarch_grave", "title": "Matriarch's Rest", "category": "elven_history", "type": "gravestone", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "shimmer",
		"content": "AELINDRA MOONWHISPER\nQueen of the Northern Groves\nLived: 847 years\n\nShe planted ten thousand trees.\nShe bore twelve daughters.\nShe spoke to every spirit by name.\n\nWhen the dead rose, she fought for three days.\nOn the fourth, she fell.\nOn the fifth, she rose with red eyes.\nOn the sixth, her own daughter struck her down.\n\nMay the spirits remember who she was,\nnot what she became."}

	e["elven_nature_spirits"] = {"id": "elven_nature_spirits", "title": "On Nature Spirits", "category": "elven_history", "type": "tablet", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "shimmer",
		"content": "Nature spirits exist within the magical field as semi-conscious energy patterns, drawn to emotions, beauty, and living things.\n\nThe more skin exposed to the field, the greater the surface for spirit interaction. This is why Elven armor is minimal. Outsiders mistake this for vanity. It is engineering.\n\nAn Elf Druid in ceremonial dress channels four times the energy of one in heavy armor. In combat, this means stronger summons, faster healing, and more potent spells.\n\nThe human soldiers find our armor 'distracting.' We find their inability to focus 'amusing.'"}

	e["elven_druid_lament"] = {"id": "elven_druid_lament", "title": "The Druid's Lament", "category": "elven_history", "type": "scroll", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "shimmer",
		"content": "When the NecroGenesis tore through the magical field, every Druid felt it - a scream that was not sound, pain that was not physical. Our connection to native animals severed instantly. The foxgliders, moonhares, canopy serpents - gone.\n\nWe wept for three days.\n\nOn the fourth, the humans brought tiny vials of Earth creature essence - DNA. Each Druid consumed one and gained ability to summon that creature's spirit. Hawks that dive like lightning. Butterflies that explode with confusion. Dragonflies fast as arrows. Vampire bats that feed on undead and return stolen life force.\n\nThey are not our animals. They are strange. But they fight beside us, and that is enough.\n\n- Druid Liralei"}

	e["elven_crystal_memory"] = {"id": "elven_crystal_memory", "title": "Memory of the First Tree", "category": "elven_history", "type": "crystal", "rarity": "legendary", "voice_provider": "elevenlabs", "voice_id": "ancient_elven",
		"content": "This crystal contains a memory predating language. When touched, you experience it:\n\nDarkness. No ground, no sky. Only the warm purple light of Giantess above. Something pushes through the soil. A seedling. It glows faintly, then brighter, then blindingly. Branches spread like rivers of light. Roots dig into the heart of the moon.\n\nAs the First Tree grows, something grows with it: awareness. The magical field being born. Spirits condensing from pure energy like rain from clouds. And in the roots, something opens its eyes for the very first time and says a word that means 'beautiful' in every language that will ever exist.\n\nYou understand now why the Elves weep when a tree falls."}

	# ===== DWARVEN HISTORY =====

	e["dwarf_deep_forge"] = {"id": "dwarf_deep_forge", "title": "The Founding of Deep Forge", "category": "dwarven_history", "type": "book", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "onyx",
		"content": "Deep Forge was founded 6,247 years ago when prospector Durin Goldnose followed a sparkite vein so deep he emerged into a natural cavern the size of a human city. Lit by phosphorescent fungi, heated by geothermal vents, riddled with the richest gold deposits ever found.\n\nDurin sent word: 'Found hole. Big hole. Much gold. Send beer.'\n\nWithin a generation, Deep Forge grew from mining camp to metropolis. Homes carved into cavern walls, bridges of stone and iron spanning underground rivers, and the Great Brewery - the social, cultural, and economic heart of civilization.\n\nIts greatest feat: the Sparkite Forge, refining raw sparkite into alchemical components for mana potions, health potions, and dozens of marvels. The processes are the most guarded secrets in Dwarven society. Any Dwarf who reveals a mana potion formula to an outsider is sentenced to 'the Quiet' - permanent exile to the deepest tunnels, alone, with only a pickaxe and their shame."}

	e["dwarf_mana_potions"] = {"id": "dwarf_mana_potions", "title": "On Mana Potions", "category": "dwarven_history", "type": "scroll", "rarity": "rare", "voice_provider": "openai", "voice_id": "onyx",
		"content": "This is NOT a recipe. It is a DESCRIPTION. Any Dwarf interpreting this as instructions answers to the Alchemists' Guild.\n\nMana potions require a seventeen-step process: refined sparkite, distilled moonwater, three proprietary catalysts, and four hours of heating at temperatures only achievable in magma forges.\n\nThe glass container is part of the potion - remove the liquid and it becomes inert within minutes.\n\nOnly Elves metabolize mana potions. Humans reject it. Dwarves are immune. Orcs glow blue for hours, which they find humiliating.\n\nThe Elves have tried to reverse-engineer the process for 4,000 years. They lack engineering knowledge. We lack magic. And so the trade continues: Dwarven potions for Elven enchantments. The longest deal on MoonRock."}

	e["dwarf_darkvision"] = {"id": "dwarf_darkvision", "title": "Dark Vision", "category": "dwarven_history", "type": "scroll", "rarity": "common", "voice_provider": "openai", "voice_id": "onyx",
		"content": "Dwarven darkvision is biology, not magic. Millennia underground evolved eyes extraordinarily sensitive to faint light - sparkite phosphorescence, thermal radiation, fungal bioluminescence.\n\nIn total darkness, a Dwarf sees as well as a Human in twilight. In typical dungeon conditions, nearly as good as day.\n\nWhere Humans need flashlights, Elves need BrightEyes, and Orcs need torches, a Dwarf just opens their eyes.\n\nOnly downside: sudden bright lights cause physical pain. A Dwarven Slayer caught in a Human flashbang is not a happy Dwarf."}

	e["dwarf_paladin_oath"] = {"id": "dwarf_paladin_oath", "title": "The Paladin's Oath", "category": "dwarven_history", "type": "tablet", "rarity": "rare", "voice_provider": "elevenlabs", "voice_id": "narrator_dramatic",
		"content": "I am the light in the deep places.\nI am the hammer that breaks the unnatural.\nI am the shield between the living and the risen.\n\nWhen I fall, my body shall not be corrupted.\nNo dark power shall raise me against my brothers.\nI shall dissolve into holy light and return to the stone.\n\nI swear by the gold in the earth,\nBy the fire in the forge,\nBy the beer in the keg,\nThat I shall stand between the living and the dead\nUntil the last skeleton crumbles\nAnd the last red eye goes dark.\n\nThis is the Oath of the Dwarven Paladin.\nOnce spoken, it cannot be unspoken.\n\n- Recited at Investiture for 3,000 years"}

	e["dwarf_brewery_report"] = {"id": "dwarf_brewery_report", "title": "Brewery Inspection", "category": "dwarven_history", "type": "note", "rarity": "common", "voice_provider": "openai", "voice_id": "onyx",
		"content": "Deep Forge Brewery - Annual Inspection\n\nVat #1 (Premium Stout): PASSED. ABV 14%. Bonus: +8% melee damage.\nVat #2 (Cave Grape Wine): PASSED. ABV 11%. Bonus: +12% damage resistance.\nVat #3 (Emergency Liquor): CONCERN. ABV 67%. Test subject punched through stone wall.\nVat #4 ('Dragon's Belch'): FAILED. Sentient. The liquid spoke to Inspector Grundin and asked to be freed. Recommend containment.\n\nNote: Three Goblins found living inside Vat #5. Appeared intoxicated and happy. Removed without incident."}

	e["dwarf_brewer_grave"] = {"id": "dwarf_brewer_grave", "title": "A Brewer's Rest", "category": "dwarven_history", "type": "gravestone", "rarity": "common", "voice_provider": "openai", "voice_id": "onyx",
		"content": "THORIN IRONBEARD\nMaster Brewer, Third Class\n\nBrewed 40,000 barrels in his lifetime.\nDrank 39,000 of them.\n\nLast words: 'Bury me with a keg.'\nWe did.\n\nWhen the dead rose, Thorin stayed down.\nEven zombies won't touch a Dwarf\nwho is 97% alcohol by volume."}

	e["dwarf_nursery_letter"] = {"id": "dwarf_nursery_letter", "title": "Deep Forge Nursery Status", "category": "dwarven_history", "type": "letter", "rarity": "uncommon", "voice_provider": "openai", "voice_id": "nova",
		"content": "To all combat personnel:\n\nThe Nursery is SECURE. All 847 pregnant females and 2,541 children evacuated to the deepest level behind seventeen sealed doors.\n\nThe females have organized their own defense. Pregnant Dwarven females are human-sized and considerably angrier than anything the undead produce.\n\nAny undead breaching the first door faces a gauntlet of hormonal Dwarven mothers. The undead do not stand a chance.\n\n- Deep Forge Emergency Command"}

	return e
